### ISSUE TITLE
dark mode is gone

### ISSUE THREAD

**Issue by yesixuan** [Mister-Hope/vuepress-theme-hope#109]
dark mode is gone in the latest version.

**Comment by Mister-Hope** [comment]
You should see the docs, the default behaviour now is `'auto'`, based on the color scheme of visitors' device. If you want to let the visitor decide  by their own, set `themeconfig.themeColor.darkmode` to `'switch'`. It's the same as previous versions behaviour.

**Comment by Mister-Hope** [comment]
Official docs appearance on my device.
![Screenshot_20200412-014244](https://user-images.githubusercontent.com/33315834/79050789-ee007980-7c5e-11ea-9209-66b50f8a0e61.jpg)

**Comment by yesixuan** [comment]
ok,thanks

**Comment by Mister-Hope** [comment]
Since the theme is allready in RC, I will make sure I marked all breaking changes next time.
