### ISSUE TITLE
The color of scroll bar didn't change when I choice a theme mode

### ISSUE THREAD

**Issue by yesixuan** [Mister-Hope/vuepress-theme-hope#110]
The color of scroll bar didn't change when I choice a theme mode.

But it workes after refresh manually.

**Comment by Mister-Hope** [comment]
On my device, it's working well. Could you give more information?

**Comment by yesixuan** [comment]
chrome 69

**Comment by Mister-Hope** [comment]
I installed chrome 69 on Win10 20H1, and the feature still seems working well. I will check the issue if I have time. At least the feature should work fine in Chrome 72+

**Comment by Mister-Hope** [comment]
I believe this issue is fixed in the newest version, could you please check it?
