### ISSUE TITLE
建议将夜间模式做成 自动、白天、夜间 三个选项

### ISSUE THREAD

**Issue by jimixy** [Mister-Hope/vuepress-theme-hope#117]
![image](https://user-images.githubusercontent.com/21176977/79085947-fd6de880-7d6c-11ea-90aa-dbb5fee0bb9e.png)
就像上图一样

**Comment by Mister-Hope** [comment]
Could you check  this?
https://deploy-preview-2301--vuepress.netlify.app/

It's a pr I contribute to the vuepress repo.

**Comment by Mister-Hope** [comment]
This feature is released in `0.1.0-rc.13`
