### ISSUE TITLE
Add your theme to official Projects-using-vuepressplugin-blog

### ISSUE THREAD

**Issue by nicpitsch** [Mister-Hope/vuepress-theme-hope#162]
I propose to add your theme to the [Projects Using @vuepress/plugin-blog](https://github.com/vuepressjs/vuepress-plugin-blog#projects-using-vuepressplugin-blog) listing at official vuepress-plugin-blog.

Thanks for providing such a great theme!

**Comment by Mister-Hope** [comment]
I already did, the pr isnot accept yet

**Comment by Mister-Hope** [comment]
i made a pr with zh docs for vuepress-plugin blog, and a pr formatting en docs, I add it in readme in the second PR

**Comment by Mister-Hope** [comment]
Theme added
