### ISSUE TITLE
[Query] Best way to change the logo based on dark mode.

### ISSUE THREAD

**Issue by e0lithic** [Mister-Hope/vuepress-theme-hope#171]
Hi,

Is there a way we can programmatically change the logo (e.g logo-light.png vs logo-dark.png) based on the dark mode? 

Thanks

**Comment by Mister-Hope** [comment]
Currently no
Is the logo you want to use too light?

**Comment by e0lithic** [comment]
The logo is in-fact dark, and hence when the theme is changed to dark mode. It almost disappears.

**Comment by Mister-Hope** [comment]
Got it, I will add a new option. A RFC request here. I am not a native English speaker, so which one do you perfer? `heroImageDark` `darkHeroImage` or `heroDarkImage`

**Comment by e0lithic** [comment]
`darkHeroImage` sounds much better. You are so prompt , stay awesome :)

On a side note will you be releasing the new release soon. Or should I build from git with latest commits to test more things?

**Comment by Mister-Hope** [comment]
I will release 0.1.1 in a few hours.

e0lithic <notifications@github.com> 于 2020年5月8日周五 12:44写道：

**Comment by Mister-Hope** [comment]
I will release 0.1.1 in a few hours.

**Comment by Mister-Hope** [comment]
A new version `0.2.0` is released. It's a minor version because a breaking change.
