### ISSUE TITLE
运行的时候会出现语言不存在并且打包时间很长

### ISSUE THREAD

**Issue by SunSeekerX** [Mister-Hope/vuepress-theme-hope#192]
![image](https://user-images.githubusercontent.com/48562733/82186549-9e783200-991d-11ea-935b-cda07968757c.png)
启动项目的时候，会报语言不存在，并且打包非常慢

**Comment by Mister-Hope** [comment]
感谢反馈

- 关于语言不存在的问题，请移步 vuepress 文档，需要在 index.styl 配置 $lang 变量，跟本主题无关。

- 关于打包慢的问题，目前也没有什么好的办法，功能加得越多打包越慢。

**Comment by Mister-Hope** [comment]
If you have any more question, feel free to open a new issue.
