### ISSUE TITLE
打包运行卡百分之40%

### ISSUE THREAD

**Issue by SunSeekerX** [Mister-Hope/vuepress-theme-hope#206]
之前有个语言不存在的原因找到了是因为我的markdown使用了不支持的语言语法
![QQ截图20200522140030](https://user-images.githubusercontent.com/48562733/82636316-e5736980-9c34-11ea-8b24-ec30779d0d77.png)

另外一个问题是，我开发运行，和打包都会出现卡40%的情况，官方的是不会，这个卡住经验来看不是因为文件多。具体原因未知，不知道作者有没有这样的情况。卡到40%是可以运行起来和打包，需要几分钟的时间才能完成。
![QQ截图20200522140039](https://user-images.githubusercontent.com/48562733/82636462-3edb9880-9c35-11ea-8787-c08f5f87d871.png)

**Comment by SunSeekerX** [comment]
已经解决了，去除markdown中不支持的流程图语法，打包运行很顺利

**Comment by Mister-Hope** [comment]
卡40%是因为那个时候vuepress需要读取你所有的markdown文件，生成 pages，读取所有markdown内容，生成frontmatter，提取标题，之后交给所有插件对 pages 数组做扩展，比如 vuepress 官方默认启用的 `last-updated` 插件会调用git读一下每个文件的提交时间，这个时候就会稍微卡一会儿，因为我这有四个插件要扩展pages数组，而且如果你的文件字符量比较大的话就会卡着。不过你成功的运行一次之后，下次读缓存就会快些，不会再重新提取标题之类的，但是所有插件还是要重新走一遍的，因为有些插件可能会根据时间，比如你把上次更新时间设置为x天x小时前，所以插件的额外处理在vuepress缓存之后，这个时候如果插件做了dirty-work就会出现问题，比如我的reading-time 阅读时间插件，就要重新读取一下你的文件并统计一遍。

不过这个还是跟你文件数量和内容量息息相关的。我跑过性能比较，目前我的插件花费的额外时间跟vuepress读取并生成文档树及相关page对象的时间比还是很小的。

**Comment by Mister-Hope** [comment]
我的主题慢主要是因为主题是 ts 写的，跟 js 写的速度的确比不了，每次都要用ts-loader处理一边，官方是直接都缓存了。这个我也没太想好怎么优化，但是等vuepress跟进vue3之后是一定会优化到跟官方主题差不多的速度的，我主题里有四五十个组件，处理一下大概两分半吧。vue2对ts的支持太差了，实在是有心无力。相关的原因可以看置顶issue。
