### ISSUE TITLE
05-25更新的开发好像有点问题

### ISSUE THREAD

**Issue by SunSeekerX** [Mister-Hope/vuepress-theme-hope#213]
启动比之前更加慢了，然后启动到控制台报了这个错误。
![image](https://user-images.githubusercontent.com/48562733/82826112-12e34000-9edf-11ea-9a4f-66ae8285681a.png)

**Comment by SunSeekerX** [comment]
这个文件是空的
![image](https://user-images.githubusercontent.com/48562733/82826290-71a8b980-9edf-11ea-84e5-4703d0a0d339.png)

**Comment by Mister-Hope** [comment]
收到，我看一下，不过目前我的博客是没有问题的。

**Comment by Mister-Hope** [comment]
我的博客有554个页面，执行一次 `vuepress dev` 的时间是2分15秒，比上个版本好像的确慢了一些。我会定位一下。

**Comment by Mister-Hope** [comment]
你感觉启动比之前慢了，主要是因为你升级主题之后，vuepress再次编译的时候，会清除大部分主题相关的缓存并重新编译并生成缓存。能否说一下你构建成功之后第二次运行 `dev` 命令的用时是多少么？

**Comment by SunSeekerX** [comment]
看到有个去除ts依赖的issue了，在使用的时候需要强制下载ts和创建一个空的文件，对项目有入侵，体验会打折扣，看能不能去除。

**Comment by SunSeekerX** [comment]
> 你感觉启动比之前慢了，主要是因为你升级主题之后，vuepress再次编译的时候，会清除大部分主题相关的缓存并重新编译并生成缓存。能否说一下你构建成功之后第二次运行 `dev` 命令的用时是多少么？

暂时还不知道，我明天试试

**Comment by Mister-Hope** [comment]
要怪就怪vue的ts写法和js写法完全不同而且没法转换吧，我当初就是从js迁移过来的。我的主题算上themeConfig 和 frontmatter 里的配置项，大概有上百，不上 ts 我自己开发的时候很容易就写错了。

别的主题都没有维护这么多插件和配置。 如果我用js重写的话，后续开发可能会出现各种小问题，调试起来及其的困难。https://vuepress-theme.mrhope.site/config/

另外你说对项目有入侵的问题，如果你使用 yarn 并善用 yarn 提供的 workspace 的话，对项目的入侵应该是很小的，你就把你的项目当成monorepo 就好了，一子项目是你的项目，另一个是文档。

之前主题是用js写的，速度还是挺快的，后来转向功能性扩展，然后又引入了 vuepress-plugin-blog 这个向组件 mixin 计算量一些计算项之后，速度就一下子慢下来了。

不过目前 vue 官方可能不一定能出 vuepress 2.0。  Evan you 新起了一个 vitepress，底层不再使用 webpack，速度更高。估计下半年就能出来，我肯定会把主题移植过去的，可以期待一下。另外 meteorlxy 也邀请了我一起开发 vuepressV2 ，地址在这里: https://github.com/vuepress/vuepress-next

vuepressV2 会直接基于Vue3，应该有望 vue 组件用ts写然后再发布之前编译成js发布，速度就会上来。

**Comment by SunSeekerX** [comment]
更新第一次启动用时2分50秒
第二次启动17秒
i5-9400F
空文件报错在另一台电脑没有出现，应该是开发环境问题。

我在想是否可以把博客那部分分离出来，因为我只用搭建一个文档网站，当然我不知道你现在是怎么处理的，如果是没有用到博客已经分离，那就没有问题了。

**Comment by Mister-Hope** [comment]
那速度应该还可以把😂

SunSeekerX <notifications@github.com> 于 2020年5月26日周二 09:35写道：

**Comment by SunSeekerX** [comment]
> 那速度应该还可以把😂 你要是不想要博客功能的话，将themeConfig.blog设置为 false就好了文档应该有写。

好了，看到了，可以关闭这个issue了，谢谢😁

**Comment by Mister-Hope** [comment]
先留着吧，我下几个版本致力一下速度优化，把一些功能默认设置成false，然后默认不加载一些功能模块，看看能否进一步提升性能。比如加密功能这种一般的确很少用到。尽量都设置成经过配置之后才开启

**Comment by SunSeekerX** [comment]
打包得时候第一次会出现这个问题，应该是你文档中enhanceApp.ts这个文件相关的，我是空的文件。
第二次打包就没有问题了。
![image](https://user-images.githubusercontent.com/48562733/82883288-cea27f00-9f74-11ea-8fc5-e352aeefb0fa.png)

**Comment by Mister-Hope** [comment]
你全局搜索一下  vuepress-type，看看是不是有地方还在引用这个包，这个包应该在0.4.0+不再使用了

**Comment by Mister-Hope** [comment]
0.4.2应该明显地缩短了打包时间，请注意0.5.0有一breaking change。
