### ISSUE TITLE
使用默认中文语言的时候报错

### ISSUE THREAD

**Issue by yesixuan** [Mister-Hope/vuepress-theme-hope#223]
![image](https://user-images.githubusercontent.com/22050621/83341399-9f459680-a315-11ea-9021-8a8e55698e86.png)

![image](https://user-images.githubusercontent.com/22050621/83341406-ab315880-a315-11ea-970d-2403d52df26a.png)

![image](https://user-images.githubusercontent.com/22050621/83341407-aff60c80-a315-11ea-8dc0-6fb3255abcf7.png)

这里读取的是小写的键值，而默认配置提供的键值是有大写的。
这个问题好久了，希望尽快恢复

**Comment by Mister-Hope** [comment]
https://www.w3.org/International/articles/language-tags/

小写是你自己填写的吧，看一下这个，标准格式就是 zh-CN

https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML

**Comment by Mister-Hope** [comment]
我会优化一下这个功能：

-  修改提示为警告而不是错误
-  在每次启动中只弹出一次
-  支持 `zh` `en` 等简写

地区语言代码后面的地区是大写的这个大部分人应该都知道，我就不打算再额外做一个逻辑判断进行大小写的修正了。

**Comment by Mister-Hope** [comment]
> 支持 zh en 等无地区语言代码

This is finally not supported because I cannot support this with `path2lang` work.

**Comment by yesixuan** [comment]
确实是我在页面的配置错了，多谢提醒！
