### ISSUE TITLE
有序列表未与正文对齐

### ISSUE THREAD

**Issue by yesixuan** [Mister-Hope/vuepress-theme-hope#224]
![image](https://user-images.githubusercontent.com/22050621/83347031-6ed11d00-a354-11ea-9eba-1f026a5e84be.png)

**Comment by Mister-Hope** [comment]
I don't think there is a bug here.
![image](https://user-images.githubusercontent.com/33315834/83347707-5a435380-a359-11ea-938e-f56808057529.png)
![image](https://user-images.githubusercontent.com/33315834/83347709-5dd6da80-a359-11ea-8f8b-ffb92a07ca72.png)

Your code, please?

**Comment by yesixuan** [comment]
## 现代哲学

现代哲学有三大方向：
1. 上帝死了；
2. 寻找根源；
3. 人类如何自处。  

### 上帝死了

::: tip
上帝死了

::: right
——尼采
:::
经过中世纪，到尼采的年代，整个西方的道德观、价值观都建立在他们的宗教信仰上面，但那时很多人已经是阳奉阴违。尼采认为，你们信仰的上帝已经被你们这些信徒杀害了，上帝名存实亡。  
后来他提出自己的超人哲学。简单说就是：上帝死了，我们自己要成为超人。西方人不能再以上帝做为借口，来遂行他个人的私欲，也包括后来巧取豪夺的殖民主义和帝国主义。

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/83934970-66ab2e80-a7e7-11ea-90fe-9c7ec39f4f4b.png)

```md
## 现代哲学

现代哲学有三大方向：

1. 上帝死了；
2. 寻找根源；
3. 人类如何自处。  

### 上帝死了

:::: tip
上帝死了

::: right
——尼采
:::
::::

经过中世纪，到尼采的年代，整个西方的道德观、价值观都建立在他们的宗教信仰上面，但那时很多人已经是阳奉阴违。尼采认为，你们信仰的上帝已经被你们这些信徒杀害了，上帝名存实亡。  
后来他提出自己的超人哲学。简单说就是：上帝死了，我们自己要成为超人。西方人不能再以上帝做为借口，来遂行他个人的私欲，也包括后来巧取豪夺的殖民主义和帝国主义。
```

**Comment by Mister-Hope** [comment]
You would better check your syntax.
