### ISSUE TITLE
pc文章目录缩放到小屏才能显示全部的toc文章目录

### ISSUE THREAD

**Issue by SunSeekerX** [Mister-Hope/vuepress-theme-hope#227]
大屏
![image](https://user-images.githubusercontent.com/48562733/83497295-d7eb9880-a4ec-11ea-9500-bed1c1217681.png)

小屏
![image](https://user-images.githubusercontent.com/48562733/83497330-e2a62d80-a4ec-11ea-8f1b-9d3f61af2a0f.png)

**Comment by Mister-Hope** [comment]
Could you please update to the newest version and see if the issue still apears?

**Comment by SunSeekerX** [comment]
> Could you please update to the newest version and see if the issue still apears?

I try to upgrade to the latest version, build it, and upload it to my server.The problem is still there

**Comment by SunSeekerX** [comment]
You can see this problem in my website [https://sunseekerx.yoouu.cn/common/resource/](https://sunseekerx.yoouu.cn/common/resource/)

**Comment by Mister-Hope** [comment]
Busy now, but i will have a look after supper, about 19:00

**Comment by Mister-Hope** [comment]
Bug confirmed, caused by only a single page in sidebar.

**Comment by Mister-Hope** [comment]
Thanks for pointing out the issue.

Besides, a suggestion here. you can show a clearer structure of your website using sidebar group.

Using sidebar group will provide associated links on sidebar, and also generates previous and next link on the bottom of the page.

Both docs of the theme and [My blog](https;//mrhope.site) and be a good example.

**Comment by SunSeekerX** [comment]
Thanks for your advice, but my site is just a documentation site.The sidebar is automatically generated.

That is enough for me. i have another blog site which is [yoouu.cn](https://yoouu.cn).

Besides, i am not good at english. hope you can get what i said.

**Comment by Mister-Hope** [comment]
v0.6.5 is released, and will solve this issue. Thanks for reporting.
