### ISSUE TITLE
There is a build error.

### ISSUE THREAD

**Issue by SunSeekerX** [Mister-Hope/vuepress-theme-hope#232]
![image](https://user-images.githubusercontent.com/48562733/83967581-892b6d80-a8f5-11ea-8318-75a61dd9a85b.png)

I upgrade to latest version and try to build my doc, i got an error.

look's like your `@mr-hope/vuepress-plugin-comment` is dependencies on "leancloud-storage": "^4.6.1".

**Comment by SunSeekerX** [comment]
sorry, i found why this error occured. i using the https://registry.npm.taobao.org for yarn registry. the "leancloud-storage": "^4.6.1" is not exits.

**Comment by Mister-Hope** [comment]
A tip here:

You can always use `https://npm.taobao.org/sync/<package-name>` to sync a package, for example `https://npm.taobao.org/sync/leancloud-storage`
