### ISSUE TITLE
新版本构建报错[Bug]

### ISSUE THREAD

**Issue by yesixuan** [Mister-Hope/vuepress-theme-hope#266]
![image](https://user-images.githubusercontent.com/22050621/86894809-2b798380-c136-11ea-982b-70c63a4318ff.png)

(undefined) ./node_modules/vuepress-theme-hope/components/SidebarLink.vue?vue&type=script&lang=ts& (./node_modules/cache-loader/dist/cjs.js??ref--15-0!./node_modules/ts-loader??ref--15-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuepress-theme-hope/components/SidebarLink.vue?vue&type=script&lang=ts&)
Module not found: Error: Can't resolve '@theme/util/sidebar' in '/Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/components'
resolve '@theme/util/sidebar' in '/Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/components'
  Parsed request is a module
  using description file: /Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/package.json (relative path: ./components)
    aliased with mapping '@theme': '/Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope' to '/Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar'
      using description file: /Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/package.json (relative path: ./components)
        using description file: /Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/package.json (relative path: ./util/sidebar)
          no extension
            /Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar doesn't exist
          .js
            /Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar.js doesn't exist
          .jsx
            /Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar.jsx doesn't exist
          .vue
            /Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar.vue doesn't exist
          .json
            /Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar.json doesn't exist
          .styl
            /Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar.styl doesn't exist
          .ts
            /Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar.ts doesn't exist
          as directory
            /Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar doesn't exist
[/Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar]
[/Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar.js]
[/Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar.jsx]
[/Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar.vue]
[/Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar.json]
[/Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar.styl]
[/Users/js/Desktop/workspace/code/node_modules/vuepress-theme-hope/util/sidebar.ts]
 @ ./node_modules/vuepress-theme-hope/components/SidebarLink.vue?vue&type=script&lang=ts& (./node_modules/cache-loader/dist/cjs.js??ref--15-0!./node_modules/ts-loader??ref--15-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuepress-theme-hope/components/SidebarLink.vue?vue&type=script&lang=ts&) 23:16-46
 @ ./node_modules/vuepress-theme-hope/components/SidebarLink.vue?vue&type=script&lang=ts&
 @ ./node_modules/vuepress-theme-hope/components/SidebarLink.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--15-0!./node_modules/ts-loader??ref--15-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuepress-theme-hope/components/SidebarLinks.vue?vue&type=script&lang=ts&
 @ ./node_modules/vuepress-theme-hope/components/SidebarLinks.vue?vue&type=script&lang=ts&
 @ ./node_modules/vuepress-theme-hope/components/SidebarLinks.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--15-0!./node_modules/ts-loader??ref--15-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuepress-theme-hope/components/Sidebar.vue?vue&type=script&lang=ts&
 @ ./node_modules/vuepress-theme-hope/components/Sidebar.vue?vue&type=script&lang=ts&
 @ ./node_modules/vuepress-theme-hope/components/Sidebar.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--15-0!./node_modules/ts-loader??ref--15-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuepress-theme-hope/components/Common.vue?vue&type=script&lang=ts&
 @ ./node_modules/vuepress-theme-hope/components/Common.vue?vue&type=script&lang=ts&
 @ ./node_modules/vuepress-theme-hope/components/Common.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--15-0!./node_modules/ts-loader??ref--15-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuepress-theme-hope/layouts/404.vue?vue&type=script&lang=ts&
 @ ./node_modules/vuepress-theme-hope/layouts/404.vue?vue&type=script&lang=ts&
 @ ./node_modules/vuepress-theme-hope/layouts/404.vue
 @ ./node_modules/.temp/internal/layout-components.js
 @ ./node_modules/@vuepress/core/lib/client/util.js
 @ ./node_modules/@vuepress/core/lib/client/app.js
 @ ./node_modules/@vuepress/core/lib/client/serverEntry.js
 @ multi ./node_modules/@vuepress/core/lib/client/serverEntry.js
Error: Failed to compile with errors.
    at /Users/js/Desktop/workspace/code/node_modules/@vuepress/core/lib/node/build/index.js:180:16
    at finalCallback (/Users/js/Desktop/workspace/code/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at /Users/js/Desktop/workspace/code/node_modules/webpack/lib/MultiCompiler.js:277:6
    at done (/Users/js/Desktop/workspace/code/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/Users/js/Desktop/workspace/code/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at /Users/js/Desktop/workspace/code/node_modules/webpack/lib/MultiCompiler.js:188:7
    at /Users/js/Desktop/workspace/code/node_modules/webpack/lib/MultiCompiler.js:270:7
    at finalCallback (/Users/js/Desktop/workspace/code/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/js/Desktop/workspace/code/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/js/Desktop/workspace/code/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/js/Desktop/workspace/code/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/js/Desktop/workspace/code/node_modules/webpack/lib/Compiler.js:271:21)
    at /Users/js/Desktop/workspace/code/node_modules/webpack/lib/Compiler.js:681:15
    at eval (eval at create (/Users/js/Desktop/workspace/code/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/js/Desktop/workspace/code/node_modules/ts-loader/dist/after-compile.js:36:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/js/Desktop/workspace/code/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c vuepress build docs
Directory: /Users/js/Desktop/workspace/code
Output:
".

**Comment by Mister-Hope** [comment]
收到，我看一下

**Comment by Mister-Hope** [comment]
我上传npm的时候漏了一个文件夹里的文件，1.6.10应该已经修复

**Comment by yesixuan** [comment]
> 我上传npm的时候漏了一个文件夹里的文件，1.6.10应该已经修复

建议作者每次发新包都自己拉下来在本地测试一下。

**Comment by Mister-Hope** [comment]
我有完善的CI测试的，上传的时候漏了文件，这个我怎么通过拉代码自己测啊😯

**Comment by yesixuan** [comment]
> 我有完善的CI测试的，上传的时候漏了文件，这个我怎么通过拉代码自己测啊😯

![image](https://user-images.githubusercontent.com/22050621/86995759-82399880-c1dc-11ea-8eb1-bb604acaf7b7.png)
更新 主题依赖不就可以测了？

**Comment by Mister-Hope** [comment]
哦我懂你意思了。我的意思是说我这种错误是没有办法在发布前检查出来的，发布后倒是可以像你这样检测一下。

**Comment by Mister-Hope** [comment]
0.7.0 已发布，构建速度有极大提升。
