### ISSUE TITLE
[Bug] 无法构建 0.6.8也是同样的问题

### ISSUE THREAD

**Issue by SunSeekerX** [Mister-Hope/vuepress-theme-hope#267]
**Describe the bug**
能启动项目，白屏，浏览器控制台报错

**Screenshots**
![image](https://user-images.githubusercontent.com/48562733/86896216-3f25e980-c138-11ea-92a9-05baeab8abc3.png)

**Comment by Mister-Hope** [comment]
收到，我看一下

**Comment by Mister-Hope** [comment]
我上传npm的时候漏了一个文件夹里的文件，1.6.10应该已经修复
