### ISSUE TITLE
0.6.9主题色配置无效[Bug]

### ISSUE THREAD

**Issue by yesixuan** [Mister-Hope/vuepress-theme-hope#269]
0.6.9主题色配置无效，
![image](https://user-images.githubusercontent.com/22050621/86989716-9de97280-c1cd-11ea-9184-2665581682c3.png)

![image](https://user-images.githubusercontent.com/22050621/86989744-afcb1580-c1cd-11ea-92d9-6d03129dbf07.png)

构建之后，颜色列表变成了一个，之前设置的主题色也变成了默认的绿色。

**Comment by Mister-Hope** [comment]
我不记得最近几个版本有动过主题色相关的文件。

一个问题，你之前有配置过主题色么，是否在stylus也正确配置了[主题色](https://vuepress-theme.mrhope.site/guide/feature/theme/#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A2%9C%E8%89%B2)

**Comment by yesixuan** [comment]
> 我不记得最近几个版本有动过主题色相关的文件。
> 
> 一个问题，你之前有配置过主题色么，是否在stylus也正确配置了[主题色](https://vuepress-theme.mrhope.site/guide/feature/theme/#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A2%9C%E8%89%B2)

stylus 没有写样式，但是之前版本主题是正常的。
顺便问一下，stylus 要写什么样式吗？你的文档里面没找到

**Comment by Mister-Hope** [comment]
我不是给你发了一个链接么😂

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/87005551-bf5c5580-c1f1-11ea-899a-85d7f19203af.png)

**Comment by yesixuan** [comment]
> 我不是给你发了一个链接么😂

加上了你说的 styl 文件，dev 正常，build 不正常
![image](https://user-images.githubusercontent.com/22050621/87006810-dc922380-c1f3-11ea-8968-c32ac9fa9f6b.png)
![image](https://user-images.githubusercontent.com/22050621/87008791-d94c6700-c1f6-11ea-9314-e6bfe406a4a3.png)

**Comment by yesixuan** [comment]
@Mister-Hope 我发现你的博客也有这个问题，不知道作者解决没？
![image](https://user-images.githubusercontent.com/22050621/87392837-cd3e1c00-c5df-11ea-81f2-f0100ca23e30.png)

**Comment by Mister-Hope** [comment]
> @Mister-Hope 我发现你的博客也有这个问题，不知道作者解决没？
> ![image](https://user-images.githubusercontent.com/22050621/87392837-cd3e1c00-c5df-11ea-81f2-f0100ca23e30.png)
> 

不好意思我这几天夏令营，过几天不忙了我马上修

**Comment by Mister-Hope** [comment]
> @Mister-Hope 我发现你的博客也有这个问题，不知道作者解决没？
> ![image](https://user-images.githubusercontent.com/22050621/87392837-cd3e1c00-c5df-11ea-81f2-f0100ca23e30.png)
> 

我看我的博客没有这个问题啊

**Comment by yesixuan** [comment]
> > @Mister-Hope 我发现你的博客也有这个问题，不知道作者解决没？
> > ![image](https://user-images.githubusercontent.com/22050621/87392837-cd3e1c00-c5df-11ea-81f2-f0100ca23e30.png)
> 
> 我看我的博客没有这个问题啊

![image](https://user-images.githubusercontent.com/22050621/87642671-673acb80-c77c-11ea-9d35-f45edf755cbe.png)
不是默认有五种颜色么？

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/87850695-c3405400-c924-11ea-8696-7879995a284d.png)
![image](https://user-images.githubusercontent.com/33315834/87850706-cafff880-c924-11ea-8b8b-33749d1e2edc.png)
我看了一下，我这边没有任何问题，emm....

**Comment by yesixuan** [comment]
我找到问题了，只有在我这Mac的chrome上面有问题，safari 正常。

> ![image](https://user-images.githubusercontent.com/33315834/87850695-c3405400-c924-11ea-8696-7879995a284d.png)
> ![image](https://user-images.githubusercontent.com/33315834/87850706-cafff880-c924-11ea-8b8b-33749d1e2edc.png)
> 我看了一下，我这边没有任何问题，emm....

我找到问题了，只有在我这Mac的chrome上面有问题，safari 正常。chrome版本 83.0.4103.116

**Comment by Mister-Hope** [comment]
那我就爱莫能助了，穷大学生没Mac，issue我关了？

**Comment by yesixuan** [comment]
> 那我就爱莫能助了，穷大学生没Mac，issue我关了？

就很奇怪，浏览器我没升过级，主题在升级你后面几个版本的时候突然就没主题色了

**Comment by yesixuan** [comment]
> 关键是后几个版本我也没动主题色相关文件

那行吧，你把issue关了吧。
