### ISSUE TITLE
修改主题色之后刷新浏览器报错[Bug]

### ISSUE THREAD

**Issue by yesixuan** [Mister-Hope/vuepress-theme-hope#284]
更改了颜色，然后刷新，你的主题从localstorage里面读取theme这个值就会报错。
这是你的博客报的错

![](https://user-images.githubusercontent.com/22050621/88005591-50a9c100-cb3c-11ea-982f-172b11dccec0.png)
![](https://user-images.githubusercontent.com/22050621/88005673-7a62e800-cb3c-11ea-9cbb-0cf5fcc04da8.png)

**Comment by Mister-Hope** [comment]
感谢准确定位问题，已经在https://github.com/Mister-Hope/vuepress-theme-hope/commit/a9114ebdae8c14245f4493b23391ce3577d2237e中修复了，我会稍候更新全新的markdown container样式，一起发布0.7.1

**Comment by Mister-Hope** [comment]
![Screenshot_20200721-115925](https://user-images.githubusercontent.com/33315834/88011330-a6389a80-cb49-11ea-8c22-9bb85ff25858.jpg)
hhh 有个函数执行顺心调了一下

**Comment by Mister-Hope** [comment]
官网现在已经正常了，我稍后就发布。
