### ISSUE TITLE
设置主题不生效

### ISSUE THREAD

**Issue by WJingC** [Mister-Hope/vuepress-theme-hope#3]
npm安装出错 于是我用了 `yarn add -D vuepress-theme-home`，然后设置 `theme: ‘hope’`,但是仍为默认主题

**Comment by Mister-Hope** [comment]
介意把你的相关repo贴一下么？我看一眼。另外主题的最原本设计就是直接与默认主题兼容。如果你不做额外配置的话主题不会有任何的更改。

**Comment by Mister-Hope** [comment]
我忘了，你试试alpha通道，我看现在最新是0.0.16@alpha1，可能有bug，你试试alpha4。最近考研基本不怎么管主题了

**Comment by Mister-Hope** [comment]
vuepress-theme-hope 已经迁移至 Typescript，代码的质量已经有进一步提升，如果有意使用，请提出新 issue 描述遇到的问题。
