### ISSUE TITLE
代码块高亮有样式 bug [Feature Request]

### ISSUE THREAD

**Issue by wenyuan** [Mister-Hope/vuepress-theme-hope#362]
描述：
代码块中，当前的高亮主题会导致标点符号（===, +, - 等）的背景色是白色，视觉上不美观。（夜间模式无此问题）
![image](https://user-images.githubusercontent.com/26686411/94381222-2a6f5580-016b-11eb-8572-7d63024f3570.png)

期望：
应该是高亮插件的主题问题，是否可以调节成其他样式兼容性较好的主题色。

拓展：
如果能在 themeOptions 中支持代码块高亮插件的主题选择就更好了。

**Comment by Mister-Hope** [comment]
我已经标记了 https://github.com/Mister-Hope/vuepress-theme-hope/issues/189

**Comment by wenyuan** [comment]
感谢答复，持续关注中

**Comment by wenyuan** [comment]
既然已经 [#189](https://github.com/Mister-Hope/vuepress-theme-hope/issues/189)  了，我这个就先 close 了。
感谢答复，持续关注中。
