### ISSUE TITLE
[Feature Request] 希望支持官方Google Analytics插件

### ISSUE THREAD

**Issue by tonnyge** [Mister-Hope/vuepress-theme-hope#370]
**Describe the feature and why you wanted**
希望能够支持官方提供的Google Analytics插件
[@vuepress/plugin-google-analytics](https://vuepress.vuejs.org/plugin/official/plugin-google-analytics.html)

**Comment by Mister-Hope** [comment]
你可以自行安装这个插件并配置它，和主题应该不冲突。我个人目前并没有用这个的需求，另外中国大陆......用百度应该会更好一点，所以我就没加在主题里。

**Comment by Mister-Hope** [comment]
你可以自己按照步骤安装试一下，如果有冲突欢迎重新打开本issue或者开一个新的。
