### ISSUE TITLE
[Feature Request] Add way to change the prefix for each icon

### ISSUE THREAD

**Issue by LocTran016** [Mister-Hope/vuepress-theme-hope#372]
**Describe the feature and why you wanted**
Hi there, in [Font Awesome 5](https://fontawesome.com/icons?from=io) have different prefix for the icon, would you mind adding feature that can add prefix to each icon
For example:
We will use `icon: "fab-accusoft"` instead of:
```js
icon: "accusoft"
    iconPrefix: "fab-",
```

**Comment by Mister-Hope** [comment]
Excuse me,  I read the doocs you provided and what I saw is that the front awesome 5 needs `fa-` prefix.

I am providing an option which can add this prefix on all of your icon.

If you are suggesting to change the default value, I am afraid I will not accept it.

The reason I am using `icon-` for default is that most of my theme users including myself are chinese, and we use [iconfont](https://iconfont.cn).

If you have other problems, welcome to decribe   more specificly.

**Comment by LocTran016** [comment]
Sorry, Mr.Hope. This is quite misleading. I don't mean to change the default value
Let's take a look at the picture below:

![image](https://user-images.githubusercontent.com/64778285/94987060-b8917480-058d-11eb-9dce-161fe7287c74.png)

As you see, each icon have different prefix: fas,far,fal,fad,fab which mean that you have to set different prefix to every individual icon instead of add this prefix on all icon

**Comment by Mister-Hope** [comment]
Got it, currently I am on a trip, I will try to provide better support after I return home.

**Comment by Mister-Hope** [comment]
I was thinking to make a better enhancement, but I am not catching up some great ideas. If you are using only one style of icon in your site, I think it's possible for you to set `iconPrefix` to `fas fa-` or `far fa-` and so on. Then it will be easy for you to set the prefix. If you are using different icons accross the site, I can not provide with some options for you to group those icons with same style.

The only thing I can enhance is that:

1. Providing three optional options: `navbarIconPrefix` `sidebarIconPrefix` `pageIconPrefix`.
2. Let all the icon key support both `string` and `string[]`

I will consider the second one as a good enhancement, But I am not sure we really need the first one.

**Comment by LocTran016** [comment]
The first one is useless anyway.
The second look better than the first one
Actually their is a small workaround for this:
```js
iconPrefix:" " //Avoid adding prefix
icon: "fas fa-camera"
icon: "far fa-camera" //Set it manually
// Don't know if adding a boolean to disable iconPrefix setting may be good as well
```

**Comment by Mister-Hope** [comment]
Hey there, below is my code:

```ts
  private get iconPrefix(): string {
    const { iconPrefix } = this.$themeConfig;

    return iconPrefix === "" ? "" : iconPrefix || "icon-";
  }
```

So I think you can just use `iconPrefix: ""` to unset the default prefix.

Besides, i am not sure if the style class must be placed before the icon type class, so,

```js
// config
iconPrefix: "fa-"

icon: "camera fas"
icon: "camera far"
```

would be better.

**Comment by Mister-Hope** [comment]
Also, I think again for the second improvement, and I decide not to do it.

**Before:**

JS:

```js
icon: "fas fa-camera"
```

Front matter:

```yaml
icon: fas fa-camera
```

---

**After:**

JS:

```js
icon: ["fas", "fa-camera"]
```

Front matter:

```yaml
icon:
  - fas
  - fa-camera
```

It's making configuration more complicated.

**Comment by LocTran016** [comment]
Besides, i am not sure if the style class must be placed before the icon type class, so I think
> 
> ```js
> // config
> iconPrefix: "fa-"
> 
> icon: "camera fas"
> icon: "camera far"
> ```
> 
> would be better.

I think so, because all fontawesome's icon have fa- and this way look better

**Comment by Mister-Hope** [comment]
I am going to close this issue since all the problems have been discussed.
