### ISSUE TITLE
如何使用百度统计

### ISSUE THREAD

**Issue by tonnyge** [Mister-Hope/vuepress-theme-hope#373]
上次Google Analytic可以使用
打算加入百度统计
因为VuePress是单页的，添加好像要改不少东西，有相关插件吗

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/95098287-1629ea80-0761-11eb-8c05-d2944d80023b.png)
https://www.npmjs.com/search?q=vuepress+baidu

我随便一搜就可以搜到两个，你自己看一下用吧，vuepress插件之间不太容易冲突，

**Comment by Mister-Hope** [comment]
另外由于我在考研，所以我不太可能，也不太有兴趣自己鼓捣出一个。建议你使用搜到的插件。
