### ISSUE TITLE
[Feature Request] Icon list

### ISSUE THREAD

**Issue by LocTran016** [Mister-Hope/vuepress-theme-hope#374]
Hi there, do you mind adding the list of supported icon (may be look like the picture below) please. Thanks

![image](https://user-images.githubusercontent.com/64778285/95005393-05bf2600-0622-11eb-94cf-cf0747de16b0.png)

**Comment by Mister-Hope** [comment]
The [https://iconfont.cn](https://iconfont.cn) site let you to create the projects of your own. And I can easily find some icons with same styles, and also it's providing icon sets.(`图标库` in Chinese)

Besides, if you use the google translate plugin, I think it's not hard for you to have a look at this site.

You can get collections in [this page](https://www.iconfont.cn/collections/index) and add them to you projects.

![image](https://user-images.githubusercontent.com/33315834/95097254-d9a9bf00-075f-11eb-874e-4f62799b8216.png)
![image](https://user-images.githubusercontent.com/33315834/95097415-0b228a80-0760-11eb-901c-1318288762e5.png)

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/95097841-86843c00-0760-11eb-9b8d-4953143f3ecd.png)
Also you can simply edit the icons to ensure they are not conflict with others.
