### ISSUE TITLE
[Note] Attention when using fontawesome

### ISSUE THREAD

**Issue by LocTran016** [Mister-Hope/vuepress-theme-hope#375]
For those who use fontawesome, please add these lines to your `index.styl`:

```styl
.iconfont
  &.fa, &.fas
    font-weight 900
```

**Comment by Mister-Hope** [comment]
Got it, I just return home from a trip, I will have a look at this issue.

**Comment by Mister-Hope** [comment]
Hey there, the only style I provided for `.iconfont` is

```styl
.iconfont
  font-weight normal
```

The reason it's breaking your icon is that you are importing the iconfont css from the template, just remove line 2

https://gitlab.com/LocTran016/present/-/blob/master/src/.vuepress/styles/index.styl

```
// import icon
@import '//at.alicdn.com/t/font_1426813_8uabl7t3rg.css'
```

**Comment by Mister-Hope** [comment]
Besides, I don't think an extra class will inflect the fontawesome icons. So if everything is working fine, I would prefer to remain the `iconfont` class. Waiting for your reply.

**Comment by LocTran016** [comment]
I have tested, may be this is a conflict with other CSS I guess (still work well with iconfont). My pen is here: https://codepen.io/loctran016/pen/XWKrjgP

**Comment by LocTran016** [comment]
> Hey there, the only style I provided for `.iconfont` is
> 
> ```stylus
> .iconfont
>   font-weight normal
> ```
> 
> The reason it's breaking your icon is that you are importing the iconfont css from the template, just remove line 2 and have a try, and I think it will work well.
> 
> https://gitlab.com/LocTran016/present/-/blob/master/src/.vuepress/styles/index.styl
> 
> ```
> // import icon
> @import '//at.alicdn.com/t/font_1426813_8uabl7t3rg.css'
> ```

I've tried this (see my [commit](https://gitlab.com/LocTran016/present/-/commit/f49c11c02641de23057ebcd23649532ddf9c1b8e)) but it seem didn't work?

**Comment by Mister-Hope** [comment]
My fault, I am linking a css file in my theme, I will publish a new version to fix it before spending some time checking out why I was linking this css.

**Comment by Mister-Hope** [comment]
I am expecting v0.7.5 fixing this issue.

**Comment by LocTran016** [comment]
This is what shown in dev state (vuepress dev src)

![image](https://user-images.githubusercontent.com/64778285/95176041-8169d000-07e6-11eb-9da2-ea9a9efc6704.png)

It look good.

**Comment by LocTran016** [comment]
The icon have been fixed:
https://loctran016.gitlab.io/present/?index=1

**Comment by LocTran016** [comment]
Hi there, after a few days I realise that there is still another bug (I'm still using FontAwesome)
As you see in the picture below, the icon next to Account rendered different from the original.
Other icon next to Cat, Tags, Timeline have the same issue. They look transparency. I've taken a look and finally realise that sth change from the solid style into regular style (change solid into transparency and add border). Because the `fas fa-tag`, `fas fa-th-large`, `fas fa-history` are 100% solid so they become completely transparency. Would you mind have a look at this? Thanks

![image](https://user-images.githubusercontent.com/64778285/95439063-4ea80f00-0981-11eb-8e0b-5d7291c4b4f3.png)

![image](https://user-images.githubusercontent.com/64778285/95438492-8f535880-0980-11eb-9cdc-1e3a60251ec1.png)

**Comment by Mister-Hope** [comment]
Got it, `font-weight: 400` is inflecting the apprence:

![image](https://user-images.githubusercontent.com/33315834/95440033-fd9d1880-098a-11eb-98a7-07acda3ed7cc.png)
![image](https://user-images.githubusercontent.com/33315834/95440047-0261cc80-098b-11eb-9b0c-3949e91a89a9.png)

**Comment by Mister-Hope** [comment]
But I am a little curious now, 
![image](https://user-images.githubusercontent.com/33315834/95440170-2fae7a80-098b-11eb-8b7e-43332ebb2970.png)

As you can see, fas class is after my iconfont class, then why my class have a higher priority? 🤣

**Comment by Mister-Hope** [comment]
I will found out a better fix later. The default iconfont needs that `font-weight: 400`

**Comment by LocTran016** [comment]
Well, there is a document about font-weight:
https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

**Comment by Mister-Hope** [comment]
> Well, there is a document about font-weight:
> https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

The problem is that while fontaswsome is changing font-weight in different types, iconfont is not setting it's font-weight, while tags like h1 and other classes in theme have different font-weight, which will affect the icon appearance, that's why I set a default  `font-weight: 400`( the same as `font-weight: normal`) to the icon. But the class priority isnot behaving what I am expected.

I didnot catch up with a better solution.

Either I remove that style and let all the iconfont users to add that style in their index.styl, or I remain the style and let all the fontawesome users to add the style I list above. It's kind of document thing.

Since more users are using iconfont, I am going to remain the style, and metion users to add extra style when using fontawesome in docs.

If you have any ideas improving the situation, welcome to reply.

If you

**Comment by Mister-Hope** [comment]
Font awesome is supported in 1.7.0. 

See https://vuepress-theme.mrhope.site/guide/feature/icon/
