### ISSUE TITLE
[Bug] Issue with vssue

### ISSUE THREAD

**Issue by LocTran016** [Mister-Hope/vuepress-theme-hope#380]
Hi there. This is my [source code](https://gitlab.com/LocTran016/present) and my [website](https://loctran016.gitlab.io/present/)
Although I have added like this into .vuepress/config.js:
```js
  themeConfig: {
    comment: {
      type: "vssue",
      platform: "gitlab",
      owner: "LocTran016",
      repo: "present",
      clientId: "396e9e1a6cfa32611e7710f8676a288c034a3eb2c85836b7e08eed2389ea0a78",
      autoCreateIssue: true,
    }, }
```
But vssue comment system still doesn't work. Can you help me with this? Thanks

**Comment by Mister-Hope** [comment]
I will.have a look at my code.

>

**Comment by Mister-Hope** [comment]
Hey bro, it's working for me with github.(I don't have a gitlab account)

![image](https://user-images.githubusercontent.com/33315834/95297096-7b3e2700-08ac-11eb-9482-94590496eea5.png)

With this config:

![image](https://user-images.githubusercontent.com/33315834/95297130-86915280-08ac-11eb-81db-f325051d9f95.png)

And I checked again that I list the gitlab deps:

https://github.com/Mister-Hope/vuepress-theme-hope/blob/master/packages/comment/package.json#L44

From this line, I am passing your config directly to vssue plugin:

https://github.com/Mister-Hope/vuepress-theme-hope/blob/master/packages/comment/lib/index.ts#L20

So I think the problem does not belong to my code.

So could you check your configuration about gitlab specially with your outh apps? If the problem still exists, maybe you can go to [vssue](https://github.com/meteorlxy/vssue/issues) for help
