### ISSUE TITLE
[Feature Request] Add reveal.js

### ISSUE THREAD

**Issue by JackJim30** [Mister-Hope/vuepress-theme-hope#384]
**Describe the feature and why you wanted**
Hi there, thanks for your wonderful theme. It look extremly good. Would mind adding reveal.js, used for creating presentation on the web. May be it could have a frontmatter like this: layout:slide for those post you want to intergrate reveal.js. Thanks

**Comment by Mister-Hope** [comment]
I spent some time looking at it. It's a awesome library, while it's lack of eco system.

I didnot find plugins to run it in vue and plugins to handle it in markdown-it.

To bring out this feature, I have to try it first on web, and then try to write packages which it's name probably something like vue-reveal and markdown-it-reveal. And that's plenty of work.

I will bring out this feature when I have time.(Maybe 2021 Jan I guss)

**Comment by LocTran016** [comment]
Hi @LarryGreen016. May be you could have a look at [hexo-theme-melody](https://github.com/Molunerfinn/hexo-theme-melody/tree/dev/layout/includes/slide) although it's for hexo, it support the reveal.js. Don't know if this may help you, Mr.Hope but here is a [template](https://github.com/Molunerfinn/hexo-theme-melody/tree/dev/layout/includes/slide) of reveal.js from that theme. Delete my message if this is off-topic

**Comment by Mister-Hope** [comment]
reveal.js is added in 1.3.0

**Comment by Mister-Hope** [comment]
1.3.1 contains bug fixes about presentation feature.

**Comment by LocTran016** [comment]
But wait, does the theme support adding some third-party plugin to revealjs? For ex, here is how to install [chartboard](https://github.com/rajgoel/reveal.js-plugins/tree/master/chalkboard):

![image](https://user-images.githubusercontent.com/64778285/96711782-4d86d100-13c8-11eb-88ef-406430ebb470.png)

**Comment by LocTran016** [comment]
Btw, Would you mind adding a `Slides` pages (creating a new post with reveal.js only instead of adding reveal.js to another post). Thanks

**Comment by Mister-Hope** [comment]
> But wait, does the theme support adding some third-party plugin to revealjs? For ex, here is how to install [chartboard](https://github.com/rajgoel/reveal.js-plugins/tree/master/chalkboard). See here for how to add the https://revealjs.com/plugins/. As for the revealjs, I don't if this would fit but if we use CDN, it may be easier to update. For example:
> 
> ```
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@latest/dist/theme/dark.css"></link>
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/highlight/monokai.css"></link>
> <script src="https://cdn.jsdelivr.net/npm/reveal.js@latest/dist/reveal.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/zoom/zoom.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/search/search.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/notes/notes.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/math/math.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/highlight/highlight.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/markdown/markdown.js"></script>
> <script>
> ```
> 
> ![image](https://user-images.githubusercontent.com/64778285/96711782-4d86d100-13c8-11eb-88ef-406430ebb470.png)

Hightlight, Markdown, Math plugin is enabled by default.

Nice catch, I will try to support plugin config in after builds.

**Comment by Mister-Hope** [comment]
> Btw, Would you mind adding a `Slides` pages (creating a new post with reveal.js only instead of adding reveal.js to another post). Thanks

The theme is design to be fit on both laptop and mobile phones. I am not sure what will the mobile screen look like in Slide pages, huge blanks will leave on the page. Maybe you can provide some ideas,

**Comment by Mister-Hope** [comment]
Besides, there is a lot of enhancement, e,g,: not bundle the plugins and themes if they are not in use. I will enhance them later.

**Comment by Mister-Hope** [comment]
BTW, you can hint the users to active a presentation and press `F`, which will enter the fullscreen now.

**Comment by LocTran016** [comment]
Well, you shouldn't provide sidebar and navbar in slide. Let's have look at my site here: https://present-520c8.web.app and the slide page is here: https://present-520c8.web.app/10/09/2020/bio/. If you display nav and sidebar, the pages would look awful. Here is what shown in mobile view

![Uploading image.png…]()

**Comment by Mister-Hope** [comment]
> Well, you shouldn't provide sidebar and navbar in slide. Let's have look at my site here: https://present-520c8.web.app (built with hexo) and the slide page is here: https://present-520c8.web.app/10/09/2020/bio/. If you display nav and sidebar, the pages may look awful. Here is what shown in mobile view, it look quite good even if you put the slide into a separate page
> 
> ![image](https://user-images.githubusercontent.com/64778285/96723118-613a3380-13d8-11eb-903b-58bb17ec000f.png)

Mobile views are vertical, so in your cases, users who enter a presentation page has to rotate his device, and hard to get back to the normal site.

Unless users are expecting a horizontal fullscreen presentation, they will feel very uncomforable when the layout suddenly changed to a total different style, and swiping in the page does nothing but changing the slides.(Touch events are catched in the reveal container).

If they accidentally enter a presentation page, they will be scaryed and probably just leaving the site.

It's a bad design for website navigation, at least a compatable vertical theme with navigation and hints should be built.

Yet, I am still going to support a pure layout, after I figure out what the vertical layout should be like.

**Comment by Mister-Hope** [comment]
By the way, reveal.js 's highlight plugin is about 700KB, so there will be a breaking change to turn it off by default in later builds.

**Comment by LocTran016** [comment]
Here is a small way to add a `menu` on reveal.js: https://github.com/denehyg/reveal.js-menu. It support adding your anything html based (including the nav bar)

![image](https://user-images.githubusercontent.com/64778285/96848291-710c5300-147e-11eb-96c5-98e5a1708e85.png)

**Comment by LocTran016** [comment]
This is what shown in vertical as well: 

![image](https://user-images.githubusercontent.com/64778285/96850520-1cb6a280-1481-11eb-957d-ec140c17f0e9.png)

**Comment by Mister-Hope** [comment]
Thanks, currently I am building a pwa enhance, I will focus on it later.

**Comment by Mister-Hope** [comment]
New `Slides` layout on portrait mode:

![image](https://user-images.githubusercontent.com/33315834/97173126-071be280-17cb-11eb-942b-4c6aa25f7200.png)

Link: https://vuepress-theme-demo.mrhope.site/slides/

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/97173199-21ee5700-17cb-11eb-9f3b-73e01e969b4e.png)

It has a better appearance under landscape mode.

**Comment by Mister-Hope** [comment]
> But wait, does the theme support adding some third-party plugin to revealjs? For ex, here is how to install [chartboard](https://github.com/rajgoel/reveal.js-plugins/tree/master/chalkboard). See here for how to add the https://revealjs.com/plugins/. As for the revealjs, I don't if this would fit but if we use CDN, it may be easier to update. For example:
> 
> ```
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@latest/dist/theme/dark.css"></link>
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/highlight/monokai.css"></link>
> <script src="https://cdn.jsdelivr.net/npm/reveal.js@latest/dist/reveal.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/zoom/zoom.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/search/search.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/notes/notes.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/math/math.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/highlight/highlight.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/markdown/markdown.js"></script>
> <script>
> ```
> 
> ![image](https://user-images.githubusercontent.com/64778285/96711782-4d86d100-13c8-11eb-88ef-406430ebb470.png)

I am going to support plugins config as the next config. In my plan, to let the output code be "tree-shaking", only a list of predefined plugins could be enabled through options.

Reveal.js has limited fucntions under markdown syntax, so I would perfer to provide an heavy predefined(or configurated) environment which is easy to write and simple in configuraion.

I am happy  to here from your opition. Would you two prefer a simple environment to write slides, or a complicated environment  which can be fully customized? @LocTran016 @JackJim30

**Comment by JackJim30** [comment]
> I am going to support plugins config in next commit. In my plan, to let the output code be "tree-shaking", only a list of predefined plugins could be enabled through options.

Well, some people may prefer plugins which aren't included in the theme (unless you include all the plugin which will make the theme become extremely bigger 😆 ) so this seem doesn't good at all. Beside this, using a reveal.js plugin isn't too hard to do that manually (even for beginners), like the picture below, you only need to inject the plugin via `<script>` tag and add that under Reveal.initialize->Plugins. For example you could add a option like this

```js
//.vuepress/config.js
presenation: {
enable: true.
plugin: {
script: {
`
<script src="plugin1 go here"></script>
<script src="plugin2 go here"></script>

`},
name: {`
Plugin1 name,
Plugin2 name
}

}}
```

and should be render like below:
```html
<!--Predefined plugins -->
 <script src="plugin1 go here"></script>
<script src="plugin2 go here"></script>
...
  Reveal.initialize({
    plugins: [ 
RevealMarkdown,
...,
Plugin1 name,
Plugin 2 name
]
  });
```
![image](https://user-images.githubusercontent.com/70789518/97195116-89ad9d80-17dd-11eb-974f-81379c836ca4.png)

**Comment by JackJim30** [comment]
> Reveal.js has limited functions under markdown syntax, so I would perfer to provide an heavily predefined(or configurated) environment which is easy to write and simple in configuraion.

Oh, yeah. I agree with you, it lack of markdown syntax so we have to use html inside markdown like this:
```md
### vuepress-theme-hope <small>v1.5</small>
<!-- .slide: data-background="#49B1F5" -->

How to add auto play media, easy, adding like this:

<video data-autoplay src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"></video>

### Steps
<!-- .slide: data-transition="concave" data-background="#C7916B" -->

#### 1. Add a slides page

<!-- .slide:data-iframe="https://slides.com" data-background-interactive -->
// ......

--

Want fragmented lines:
- First line <!-- .element: class="fragment" data-fragment-index="2" -->
_ Second line <!-- .element: class="fragment" data-fragment-index="1" -->
// ......

---

#### 2. Add the layout type
<!-- .slide: data-transition="fade" data-background="#00C4B6" -->
```
And this doesn't too hard because it just use basic syntax.

**Comment by LocTran016** [comment]
> ![image](https://user-images.githubusercontent.com/33315834/97173199-21ee5700-17cb-11eb-9f3b-73e01e969b4e.png)
> 
> It has a better appearance under landscape mode.

This look really good but do you mind adding a option that will put all post with frontmatter: `layout: slide`(those post which using reveal.js) into another folder (maybe present or slide,...:/slide or /present) instead of showing them in the main page.

**Comment by Mister-Hope** [comment]
> > ![image](https://user-images.githubusercontent.com/33315834/97173199-21ee5700-17cb-11eb-9f3b-73e01e969b4e.png)
> > 
> > It has a better appearance under landscape mode.
> 
> This look really good but do you mind adding a option that will put all post with frontmatter: `layout: slide`(those post which using reveal.js) into another folder (maybe present or slide,...:/slide or /present) instead of showing them in the main page.

I don't think I will build this feature.

 This is totally up to you. You can just create a slides folder or a presentation folder and put all your pages using the layout slides there.

**Comment by Mister-Hope** [comment]
But I may build a feature that is like an article list which can show all the slides pages.

**Comment by Mister-Hope** [comment]
> > I am going to support plugins config in next commit. In my plan, to let the output code be "tree-shaking", only a list of predefined plugins could be enabled through options.
> 
> Well, some people may prefer plugins which aren't included in the theme (unless you include all the plugin which will make the theme become extremely bigger 😆 ) so this seem doesn't good at all. Beside this, using a reveal.js plugin isn't too hard to do that manually (even for beginners), like the picture below, you only need to inject the plugin via `<script>` tag and add that under Reveal.initialize->Plugins. For example you could add a option like this
> 
> ```js
> //.vuepress/config.js
> presenation: {
> enable: true.
> plugin: {
> script: {
> `
> <script src="plugin1 go here"></script>
> <script src="plugin2 go here"></script>
> 
> `},
> name: {`
> Plugin1 name,
> Plugin2 name
> }
> 
> }}
> ```
> 
> and should be render like below:
> ```html
> 
>  <script src="plugin1 go here"></script>
> <script src="plugin2 go here"></script>
> ...
>   Reveal.initialize({
>     plugins: [ 
> RevealMarkdown,
> ...,
> Plugin1 name,
> Plugin 2 name
> ]
>   });
> ```
> ![image](https://user-images.githubusercontent.com/70789518/97195116-89ad9d80-17dd-11eb-974f-81379c836ca4.png)
> 

 Hey, there it is easy using the head config in vuepress  to inject script tags.

 But they will be injected in the head part of the documentation while loading them, the rest of the documentation is not fully loaded. So review.js  Cannot be initialize  Because in some slow network they cannot accept dom in head tags. So it is impossible for users to  Write their codes and ejected to tag to initialize.

 Meanwhile, the head options will be injected to all the pages and that's not what we are expecting. When viewing normal pages, we should not let the website to load the review js, Because it's too big and will take seconds to load.

 Well,  You cannot let users to configure functions in front matter. And it's unsafe to eval strings the in front matter to create a new function. 

Though it's possible for users to pass functions and variables in the themeConfig, （they can install and npm package  and pass them in the themeConfig. And it's possible for me to use these variables and pass it as the plugin option of review js） But if you try doing this, you will get error when doing the server rendering because some of the plugins are sexy documents window or navigate her in their codes.（ In my theme, I'm importing them on the mounted life cycle in the presentation component.）

 So I can not catch up with an idea  to let users importing the plugins and letting me to pass these penguins when initializing review js in my components.  （evaling a function string from the user is not acceptable for me）

**Comment by Mister-Hope** [comment]
So it's only possible for me to give users some options which they can enable specific plugins in the options.  

 To do that, I will using the if statement to judge whether or not import a plugin in my mounted life cycle of component.

And I will define the user option as a constant, so that webpack can just drop them if the if statement are false and the disabled plugins will not appear in the final bundled code.

**Comment by JackJim30** [comment]
> So it's only possible for me to give users some options which they can enable specific plugins in the options.
> 
> To do that, I will using the if statement to judge whether or not import a plugin in my mounted life cycle of component.
> 
> And I will define the user option as a constant, so that webpack can just drop them if the if statement are false and the disabled plugins will not appear in the final bundled code.

Oh, quite sad to here this. But how many plugin do you think you can (should) add to the theme? Thanks

P/S: A small note that plugins chalkboard need fontawesome so if you add chalkboard, add reminder that it require fontawesome

**Comment by LocTran016** [comment]
> > > ![image](https://user-images.githubusercontent.com/33315834/97173199-21ee5700-17cb-11eb-9f3b-73e01e969b4e.png)
> > > It has a better appearance under landscape mode.
> > 
> > 
> > This look really good but do you mind adding a option that will put all post with frontmatter: `layout: slide`(those post which using reveal.js) into another folder (maybe present or slide,...:/slide or /present) instead of showing them in the main page.
> 
> I don't think I will build this feature.
> 
> This is totally up to you. You can just create a slides folder or a presentation folder and put all your pages using the layout slides there. If you are placing a slide page in your other articles or documentations, I don't think you really need to move it to a specific folder. Well, if you are just creating some presentations, you can just place them in the specific folder you like.
> 
> So could you tell me why are you want to move all the pages using the layout slides in a specific folder?

Oh, don't know if you get my idea 🤔. Well, have a look at my repo [here](https://github.com/LocTran016/fpr/tree/master/src), although I have put 2 post in different folders, both of them are shown in the homepage (or landing page, root page, don't know what to call that) so I'm thinking of adding a option that slide posts will be hided in the homepage and then shown in sub directory for example the text-only post (post which doesn't use pure layout of reveal) will shown here abc.com/ and then the slide post will be shown in abc.com/present or that kind of things to make site look better (text-only and slide post are separated)
![image](https://user-images.githubusercontent.com/64778285/97273991-9924f900-1866-11eb-8532-16dbcc8594f6.png)

**Comment by Mister-Hope** [comment]
In the next version, a presentation icon will appear next to the page title to mark it as a presentation.

Just like this encryption page:
![image](https://user-images.githubusercontent.com/33315834/97281344-59ffa380-1878-11eb-8479-c2d13a2bd6c1.png)

In my ideas, I would expecting the home page to display all types of pages, and you can view them in group by navigating to `/article/`(will filter slides in plan) `/category/` `/tag/` `/timeline/` and `/slides/`(in plan).

**Comment by Mister-Hope** [comment]
`/slide/` and `/encrypt/` are added, while I am changing the layout name from `Slides` to `Slide` in `1.5.0-beta1`.

Beta 2 will support plugins, and maybe there will be breaking changes in `vuepress-md-enhance` 's options.

**Comment by Mister-Hope** [comment]
I have some issues importing the plugin.

After hours of debugging, I suddenly release that `reveal.js-plugin` isn't been updated for a while, and the code is not the same as those in the repo.

Also, none of these plugins are valid module(none commonjs nor es module)

So finally, I am going to rewrite them with Typescript. In the next 60 days I would be very busy. So I will leave this feature to next year, while focused on bug fixing and official plugin support today and tomorrow, with 1.5.0.

And since the theme is supporting reveal.js now, I am going to close this one. While I am going to open a new one #437  about 3rd-party plugin support. Welcome to share your opinions and suggestions there.
