### ISSUE TITLE
[Feature Request] Add option to change icon's style in dark/light mode

### ISSUE THREAD

**Issue by LocTran016** [Mister-Hope/vuepress-theme-hope#385]
Hi there, I have seen that the theme have setting to display another logo in dark mode, would you mind adding a setting to display another icon in darkmode like this
icon:"sth"
darkIcon: "some others things" //Display another icon in darkmode
Thanks

**Comment by Mister-Hope** [comment]
This feature is not hard to add. But I am curious about why you need this feature.

Logos can be images which it's color can be too light in darkmode(or too dark in lightmode), so I added that darkLogo option.
But font icons only have shapes, and it's color should be adjusted when switching between darkmode and lightmode.

So why do you need to change to another icon in darkmode?

**Comment by LocTran016** [comment]
Oh, sorry. I though that you can add a darkIcon and then add darkStyle and Style (for light mode) to make it render like this: `<i class="fal fa-quidditch" style="color: #f06595;"></i>` but I h the a better idea that we just need to add 
`darkStyle` (for styles in darkmode) and `Style`(for lightmode)

## Why

Well, have a look at my site, the reddit icon in darkmode look doesn't good because of its color but in lightmode, it look great in lightmode so adding a way to change the color of icons in dark/light mode is great

![image](https://user-images.githubusercontent.com/64778285/95650156-ed607700-0b0b-11eb-9c11-334fb1e2d496.png)


![image](https://user-images.githubusercontent.com/64778285/95650124-a96d7200-0b0b-11eb-9c28-4b987f4d71a6.png)

**Comment by Mister-Hope** [comment]
Do you like the icon color or not?

If not, I think it's possible for you to add in your `index.styl`

```styl
.iconfont::before
  color inherit
```

If above has issues, you can add important:


```styl
.iconfont::before
  color inherit!important
```

**Comment by LocTran016** [comment]
I really love the icon color in light mode but it doesn't look good at darkmode so I just want to change the icon's color in darkmode into another color

**Comment by Mister-Hope** [comment]
Besides, I regard these icons as decorations, and I am not expecting users take a look time configurating them. If you do want a full control to the icon, I will add some options like iconStyle add darkIconStyle.

**Comment by Mister-Hope** [comment]
Hey here, I just realize you are configuring contact. There is a component for you to add those links:

![image](https://user-images.githubusercontent.com/33315834/95650435-4fbe7500-0b16-11eb-90e1-12184b75eeb4.png)
![image](https://user-images.githubusercontent.com/33315834/95650445-5947dd00-0b16-11eb-9bb6-7264c54fbc69.png)

**Comment by LocTran016** [comment]
Oh, yeah I know that but it doesn't support some platform: gitlab, bitbucket, reddit so I choose to add a small dropdown item on the nav bar

**Comment by Mister-Hope** [comment]
You can leave the icons you want, I can add them in the next version.

**Comment by LocTran016** [comment]
Can you add discord as well

![image](https://user-images.githubusercontent.com/64778285/95650807-24388c00-0b10-11eb-8838-88fd08dda164.png)

**Comment by Mister-Hope** [comment]
The four icons were added in 0.8.0
