### ISSUE TITLE
[Feature Request] Add ShareThis

### ISSUE THREAD

**Issue by LocTran016** [Mister-Hope/vuepress-theme-hope#386]
Hi there, would mind adding ShareThis for these social share buttons on the left. Only the content after `pubid` change.
![image](https://user-images.githubusercontent.com/64778285/95651116-226fc800-0b12-11eb-9805-0ec4020b5ffd.png)

![image](https://user-images.githubusercontent.com/64778285/95651173-99a55c00-0b12-11eb-9815-a1ec834ef37c.png)

![image](https://user-images.githubusercontent.com/64778285/95651153-74b0e900-0b12-11eb-9d24-4e6e75ddbbad.png)

**Comment by Mister-Hope** [comment]
I have a plan to build a plugin which will add a set of share buttons to the page.

Almost all the media on share this cannot access in china, which means, most of the users don't need it. 

Before I build my share plugin, you can create a plugin which can enable sharethis. It's not hard.

**Comment by LocTran016** [comment]
Excuse me, WOuld you mind building the plugin? I'm not good at coding so this quite hard for me. Thanks

**Comment by Mister-Hope** [comment]
vuepress-plugin-add-this is built.

**Comment by Mister-Hope** [comment]
Wait a minute, I found a typo.

**Comment by Mister-Hope** [comment]
0.8.0 vesion lands with `vuepress-plugin-add-this`.
