### ISSUE TITLE
[Bug] Issue with my site

### ISSUE THREAD

**Issue by LocTran016** [Mister-Hope/vuepress-theme-hope#387]
**Describe the bug**

Hi there. I've added a `themeConfig.hostname` but the sitemap still doesn't work

![image](https://user-images.githubusercontent.com/64778285/95680416-ba99aa00-0c03-11eb-8dbf-0956132a9db7.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/64778285/95680364-50810500-0c03-11eb-8a3a-a067b070b5f8.png)

**Additional context**

* [My repo](https://github.com/LocTran016/present/tree/master)
* [My site](https://loctran016.gitlab.io/present/)

**Comment by Mister-Hope** [comment]
Could you please clear the cache and try again?

**Comment by LocTran016** [comment]
Doesn't help. I've tried vuepress build src --no-cache but still doesn't work

![image](https://user-images.githubusercontent.com/64778285/95684132-9cd73f80-0c19-11eb-9fd5-5555e7368dda.png)

**Comment by Mister-Hope** [comment]
but the template runs well, see https://github.com/Mister-Hope/vuepress-theme-hope-template/runs/1238745335 for action log.

**Comment by Mister-Hope** [comment]
I tried, but I really cannot reproduce this "bug or maybe not"

**Comment by LocTran016** [comment]
Does adding other vuepress-plugin affect this? My site have some more plugin than your site.

**Comment by LocTran016** [comment]
I have tried gitlab as well https://loctran016.gitlab.io/present/ but doesn't work

**Comment by LocTran016** [comment]
Well, I have found that the add this, comment(vssue) and sitemap are not working. This is quite strange because I have set all of them correctly (I have used the copy button to get clientID so no way it will be wrong, all others are set correctly as well.

**Comment by Mister-Hope** [comment]
Perhaps vssue access hostname when in use then clear the value. I will have a look later.

**Comment by Mister-Hope** [comment]
I clone the vssue repo, and I didnot found any problems. 
![image](https://user-images.githubusercontent.com/33315834/95776134-53105700-0cf6-11eb-9c81-eb08ec9ad696.png)
I don't think there are issues in my code. Maybe you can come to Vssue for help.

By the way, do you find why gitlab is not working?

**Comment by LocTran016** [comment]
No, For the vssue, it used to working on my another site (different clienID) mean there isn't any problem with vssue. Don't know why there isn't anything wrong with your code and my config, but add this, vssue, sitemap still doesn't working which is really strange

**Comment by Mister-Hope** [comment]
> No, For the vssue, it used to working on my another site (different clienID) mean there isn't any problem with vssue. Don't know why there isn't anything wrong with your code and my config, but add this, vssue, sitemap still doesn't working which is really strange. For sharethis, it only working in dev mode (the web opened in the left)
> 
> ![image](https://user-images.githubusercontent.com/64778285/95820545-736dff00-0d52-11eb-8371-a12050b41678.png)

Sharethis request is blocked by the browser, because github and gitlab will refuse some Cross site Request.

![image](https://user-images.githubusercontent.com/33315834/95842084-b3e07380-0d78-11eb-8bbb-259927ea3907.png)

My theme cannot set the request headers. To let this work, maybe you should deploy it on your own server.

**Comment by Mister-Hope** [comment]
It do seems that vssue is imcopatable with my theme. But there are not bugs in my code, and I do not have time to read through vssue repo. So I suggest using valine instead of vssue. Feel free to open new issues if you found new problems.

**Comment by Mister-Hope** [comment]
By the way, if you want to learn more about add-this plugin problems, search "Cross-domain Request" and “Same-origin Policy”  “CSRF”  to make a simple view. Then you can understand what's CORS and why this CORS is blocked.

**Comment by Mister-Hope** [comment]
I will evel the code as a work around.

**Comment by Mister-Hope** [comment]
1.0.0-0 has release and fixed add-this plugin.

**Comment by Mister-Hope** [comment]
Hi, can you help with your language support? 😄 

https://github.com/Mister-Hope/vuepress-theme-hope/blob/master/packages/shared-utils/lib/i18n/config.ts

**Comment by LocTran016** [comment]
Yes, I will
