### ISSUE TITLE
看了你的主题，感觉非常好看。如果能加上这个功能就更好了...

### ISSUE THREAD

**Issue by yesixuan** [Mister-Hope/vuepress-theme-hope#40]
目前的侧栏会把文章和文章下面的标题提取出来放到侧边栏，形成树结构。

但是这样会显得有些混乱，尤其是在层级比较多的情况下。

所以希望提供这样的功能选项：

左侧只显示文章列表，
文章的右侧给一片固定的区域展示文章内部提取出来的标题结果。

有一些例子可以参考一下：
https://d.umijs.org/guide/control-route-generate

https://www.yvescoding.com/rcpress/config/

类似这种
![image](https://user-images.githubusercontent.com/22050621/76700866-b4d3f880-66f6-11ea-9732-afe08356f7f2.png)

**Comment by Mister-Hope** [comment]
感谢建议，我会考虑的，主要是antd和现在页面其他的元素风格不太统一，自己写一个太麻烦。

**Comment by Mister-Hope** [comment]
This issue is moved to #75. Thanks for the advice again.

**Comment by Mister-Hope** [comment]
This feature is add in `0.6.2`
