### ISSUE TITLE
image url issue

### ISSUE THREAD

**Issue by khs1994** [Mister-Hope/vuepress-theme-hope#406]
* https://vuepress.mirror.docker-practice.com/install/windows/
* https://raw.githubusercontent.com/yeasy/docker_practice/master/install/windows.md

生成页面图片路径有问题，这个问题算是 bug,还是该改源 md 中的图片路径

**Comment by Mister-Hope** [comment]
收到，我看一下。

**Comment by Mister-Hope** [comment]
你应该把所有图片链接使用 `./` 开头。
