### ISSUE TITLE
[Feature Request] the previous version of copyCode plugin style looks better

### ISSUE THREAD

**Issue by wenyuan** [Mister-Hope/vuepress-theme-hope#431]
描述：
如果用于文档管理，上一个版本的代码复制按钮看起来更好些，两个方面考虑：
1. 代码复制按钮的放置位置，和代码块语言类型放在一起占的空间小，且属于同一类功能，大部分技术网站也是这么布局的。
2. 复制成功后的提示，新版本增加了一个鲜花的 emoji，用于官方文档的话显得不那么正式了。

如果用于个人博客，那自然现在的样式会更酷炫些。

期望：
小建议，可以考虑下。

**Comment by Mister-Hope** [comment]
收到，这边看一下能不能加个配置项。

**Comment by Mister-Hope** [comment]
我将会添加一个纯净模式，请见 #438 ，此功能也会在这个issue追踪。

另外我在考研hhh，所以这功能可能要到明年1月份才能上线。

之前我用的是 `vuepress-plugin-one-click-copy`，目前你可以安装它，之后设置:

```js
module.export = {
  themeConfig: {
    copyCode: false
  },
  plugins: [
    'one-click-copy'
  ]
};
```

来暂时解决这个问题。

**Comment by wenyuan** [comment]
感谢回执，加油！
