### ISSUE TITLE
[Question] The right side TOC doesn't utilize the page well.

### ISSUE THREAD

**Issue by piyush-das** [Mister-Hope/vuepress-theme-hope#448]
Hi,

While comparing the right hand sidebar with gitbook or say  [vdoing](https://doc.xugaoyi.com/vuepress-theme-vdoing-doc/pages/793dcb/) it seems that the sidebar utilizes the page much better.
![Screenshot from 2020-11-12 18-55-52](https://user-images.githubusercontent.com/68941107/98945592-ba4d4100-2518-11eb-8cc6-28883b207ed1.png)

While in the current theme it appears as if the sidebar almost seems irrelevant. Are there any configurations for achieving layout as above?
![Screenshot from 2020-11-12 18-54-38](https://user-images.githubusercontent.com/68941107/98945475-91c54700-2518-11eb-92a2-638272ff72b4.png)

Thanks for the great work :)

**Comment by Mister-Hope** [comment]
Will adjust in newer version
