### ISSUE TITLE
[Bug] lastUpdate config gets overridden

### ISSUE THREAD

**Issue by zikeji** [Mister-Hope/vuepress-theme-hope#455]
When using the theme, the theme by default adds plugins.  Because @mr-hope/vuepress-plugin-sitemap and @mr-hope/vuepress-plugin-seo both require @mr-hope/@mr-hope/vuepress-plugin-last-update the last-update plugin ends up getting specified 3 times, and only the options from the last time get passed to the plugin. This means any options passed in the config.ts/js file get ignored.

One solution could be to conditionally load that plugin in the sitemap and seo plugins. That or rely on the themeConfig object and not the options object.

The workaround is to manually add the last-update plugin with the config there. so that is the last time loading it.

**Comment by Mister-Hope** [comment]
I am not understanding what you are saying, especially your solution.

`@mr-hope/vuepress-plugin-seo`  and `@mr-hope/vuepress-plugin-sitemap` does require `@mr-hope/vuepress-plugin-last-update` and it can overide the users plugin option. So now they are all reading `themeConfig.lastUpdate`, to make sure the config won't be overidden.

Both the [theme-demo](https://vuepress-theme-demo.mrhope.site/) and [my blog](https://mrhope.site/) is working fine when setting `themeConfig.lastUpdate` now.

**Comment by zikeji** [comment]
My apologies - I hadn't yet seen the new release. It appears you fixed the bug a few hours before I opened my issue. You fixed it with commit 30aef72de385af7c5ac633ef0cd17daccafb9a60.
