### ISSUE TITLE
[Bug] missing style with copy-code plugin

### ISSUE THREAD

**Issue by piyush-das** [Mister-Hope/vuepress-theme-hope#456]
Hi,

I am trying to use the `copy-code` plugin with the default vuepress theme. However, in that case it seems like when the page is scrolled the code section properly gets under the navbar but the copy-code icon goes on top of the navbar.
![Screenshot from 2020-11-19 13-45-18](https://user-images.githubusercontent.com/68941107/99639527-b61ba900-2a6d-11eb-9a96-5ee9e0072ac9.png)

However, this behaviour doesn't happen when it is used with your theme. Can you plesae let me know where I am going wrong?

Thanks

**Comment by Mister-Hope** [comment]
I will fix it very soon. Thanks.

**Comment by Mister-Hope** [comment]
It should be fixed in 1.6.1

**Comment by Mister-Hope** [comment]
I'm going to close this issue.

If you still meet problems, feel free to reopen It.
