### ISSUE TITLE
[Question] 代码块中如何高亮部分行

### ISSUE THREAD

**Issue by puppetsheep** [Mister-Hope/vuepress-theme-hope#460]
文档中页面配置中高亮了关键项，但未给出如何高亮代码指定行的语法

**Comment by puppetsheep** [comment]
尝试了一些，应该是这样吧？
````
```js {1-2,4}
1
2
3
4
```
````

**Comment by Mister-Hope** [comment]
https://vuepress.vuejs.org/zh/guide/markdown.html#%E4%BB%A3%E7%A0%81%E5%9D%97%E4%B8%AD%E7%9A%84%E8%A1%8C%E9%AB%98%E4%BA%AE

类似的问题建议看官方文档。我不可能把整个官方文档都搬过来。
