### ISSUE TITLE
[Question] 在本主题中如何加入自定义的vue组件?

### ISSUE THREAD

**Issue by yanglr** [Mister-Hope/vuepress-theme-hope#489]
**Describe your question**
What are you confusing about?

目前使用`npm i -D vuepress-theme-hope`命令安装`vuepress-theme-hope`主题之后，`vuepress-theme-hope`主题的相关文件会自动放到`node_modules`文件夹中，而`node_modules`文件夹已经被加到了 .gitignore 文件中。

此时，即使根据个人需求改掉或增加部分 .vue 文件，也是无法push到远程的~

请问有什么办法加入自定义的vue组件嘛? 谢谢~

据了解，另一个vuepress的vdoing主题配置文件[`config.js`](https://github.com/xugaoyi/vuepress-theme-vdoing/blob/master/docs/.vuepress/config.js)中提供了两种配置方案 - github仓库和本地 theme 文件夹两种方式，vdoing主题如果用本地 theme 文件夹的方式就可以根据个人需求改掉或增加部分 .vue 文件，达到自定义的目标。

**Comment by Mister-Hope** [comment]
你可以自由继承本主题，相关文档： https://v1.vuepress.vuejs.org/zh/theme/inheritance.html

本主题支持eject，相关文档：https://v1.vuepress.vuejs.org/zh/api/cli.html#eject
这将直接将本主题的全部文件复制出来并本地主题，你可以任意修改并加入版本追踪

**Comment by yanglr** [comment]
好的，感谢大佬，我试试看~

**Comment by yzhang921** [comment]
请问为什么eject失败，

  "devDependencies": {
    "vuepress": "^1.8.2",
    "vuepress-theme-hope": "^1.18.4"
  },

```
$ vuepress eject-hope aaa
Unknown command: eject-hope aaa

tip Did you miss to specify the target docs dir? e.g. vuepress eject-hope [targetDir].
tip A custom command registered by a plugin requires VuePress to locate your site configuration like vuepress dev or vuepress build.

```

**Comment by Mister-Hope** [comment]
> 请问为什么eject失败，
> 
> "devDependencies": {
> "vuepress": "^1.8.2",
> "vuepress-theme-hope": "^1.18.4"
> },
> 
> ```
> $ vuepress eject-hope aaa
> Unknown command: eject-hope aaa
> 
> tip Did you miss to specify the target docs dir? e.g. vuepress eject-hope [targetDir].
> tip A custom command registered by a plugin requires VuePress to locate your site configuration like vuepress dev or vuepress build.
> ```

想要使用这个命令，你需要先配置好项目。命令是由vuepress提供的，这意味着你必须在一个启用了主题的vuepress项目运行该命令，否则“找不到vuepress命令”或“vuepress读取不到主题提供的扩展命令”

**Comment by yzhang921** [comment]
已经正常运行起来了

**Comment by Mister-Hope** [comment]
仓库链接给一下？

**Comment by Mister-Hope** [comment]
其实你可以手动拷贝文件的，没有什么太大区别。

**Comment by yzhang921** [comment]
还没有部署到外网

![image](https://user-images.githubusercontent.com/6037522/123798617-f0a9c600-d919-11eb-9347-9da884f8e0bd.png)


默认主题继承，我成功操作过，hope主题其实只要配置在theme下面继承启动都有问题 

```
module.exports = {
    extend: 'vuepress-theme-hope'
}
```


```
cjs.js?!./node_modules/postcss-loader/src/index.js?!./node_modules/stylus-loader/index.js?!./node_modules/.temp/style.styl:1 Uncaught Error: Module build failed (from ./node_modules/stylus-loader/index.js):
Error: /Users/peter/Documents/workspace/vuejs-projects/chuguo-doc/node_modules/vuepress-theme-hope/styles/normalize.styl:1:10
   1| @require '~@theme/styles/fonts/crimson.css'
---------------^
   2| @require '~@mr-hope/vuepress-shared/styles/wrapper'
   3| 
   4| html, body

failed to locate @require file ~@theme/styles/fonts/crimson.css
```

**Comment by Mister-Hope** [comment]
请见首页关于 config 函数的说明

**Comment by Mister-Hope** [comment]
另外如果你的确需要继承，你还需要显示指定继承者主题的目录位置并将其传递到 theme 中，否则 config wrapper 函数会自动将 theme
 设置为 `'hope'`。

**Comment by Mister-Hope** [comment]
另外关于 eject-hope 的问题，麻烦你使用 `yarn create vuepress-theme-hope [dir]` 创建一个模板，试一下模板可不可以直接弹出。如果模板可以，那就要麻烦你自己找问题了。

**Comment by yzhang921** [comment]
有点不熟悉，能详细给个案例出来吗，多谢了

**Comment by yzhang921** [comment]
我不是用的npm init vuepress-theme-hope [dir] 命令创建的项目，在默认项目基础上，常规的npm install hope主题，用config函数配置

**Comment by Mister-Hope** [comment]
https://vuepress-theme-hope.github.io/zh/#%F0%9F%9A%80-%E4%BD%BF%E7%94%A8

```js
// .vuepress/config.js
const { resolve } = require('path')
const { config } = require("vuepress-theme-hope");

module.exports = config({
  // your config here
  theme: resolve(__dirname, 'theme'),
  extends: 'hope',
});
```

**Comment by Mister-Hope** [comment]
> 我不是用的npm init vuepress-theme-hope [dir] 命令创建的项目，在默认项目基础上，常规的npm install hope主题，用config函数配置

我的意思就是模板你可以试一下，一个月前肯定是可以的，而且我最近没动过相关文件。如果可以就说明锅不在我这，我也看不到仓库你只能自己排查问题，如果不可以欢迎反馈给我，我看看是不是哪个工具链上的包出了点啥问题。

**Comment by yzhang921** [comment]
> > 我不是用的npm init vuepress-theme-hope [dir] 命令创建的项目，在默认项目基础上，常规的npm install hope主题，用config函数配置
> 
> 我的意思就是你可以用模板建一个新项目试一下，一个月前肯定是可以的，而且我最近没动过相关文件。如果可以就说明锅不在我这，我也看不到仓库你只能自己排查问题，如果不可以欢迎反馈给我，我看看是不是哪个工具链上的包出了点啥问题。

这个命令是可以的没有问题，今天白天就测试了，我是一天是用的默认主题，自己集成，后面看到你这个主题比较全，就用常规的模式操作了一下

我一会儿把代码发布出来，还请帮忙看下

**Comment by yzhang921** [comment]
https://gitee.com/cboard_beta/chuguo-doc

**Comment by yzhang921** [comment]
https://github.com/TuiQiao/chuguo-doc

**Comment by yzhang921** [comment]
eject 成功了，原来vuepress eject-hope [target dir]，
target dir: 必须是.vuepress所在的文件夹才可以

**Comment by Mister-Hope** [comment]
> https://vuepress-theme-hope.github.io/zh/#%F0%9F%9A%80-%E4%BD%BF%E7%94%A8
> 
> ```js
> // .vuepress/config.js
> const { resolve } = require('path');
> const { config } = require("vuepress-theme-hope");
> 
> module.exports = config({
>   // your config here
>   theme: resolve(__dirname, 'theme'),
>   extends: 'hope',
> });
> ```
> 

这是继承的具体方式。
