### ISSUE TITLE
[Bug]运行时输入错误日志，以及打包不成功问题

### ISSUE THREAD

**Issue by hanjunqiang** [Mister-Hope/vuepress-theme-hope#520]
[运行时后台报错日志](https://mrhan.lanzous.com/iPHMuk09qch)
[打包时报错日志](https://mrhan.lanzous.com/irTo0k09ora)

**Comment by Mister-Hope** [comment]
Sorry for the late reply.

Please update to the latest version of vuepress, exce `yarn upgrade` (or `npm update`) and try again.

If the problem still exists, consider disable all the 3rd party plugins, if still exists, please give me your log.

All the problems are not related to my theme files, instead they are from vuepress deps.
