### ISSUE TITLE
[Bug] 新版本Build之后生成的js文件包含中文

### ISSUE THREAD

**Issue by sonderlau** [Mister-Hope/vuepress-theme-hope#523]
**Describe the bug**

使用最新版 `1.7.9` 主题 并使用 `vuepress build docs` 之后
`assets/js`目录下的所有生成的js文件都包含文章的标题，有的标题包含中文，在Linux服务器部署的时候会出现问题，而原版则在标题的位置放数字

**Screenshots**

![image](https://user-images.githubusercontent.com/12829325/103536274-1c2b8680-4e8a-11eb-9f39-093f837ad715.png)

![image](https://user-images.githubusercontent.com/12829325/103536416-601e8b80-4e8a-11eb-8a86-023acd3dd049.png)

**Additional context**
Vuepress 版本 `1.7.2`

**Comment by sonderlau** [comment]
附：我是从` 0.7.2 `一下升到了 `1.7.9` 版本

**Comment by Mister-Hope** [comment]
This behavior is expected. A file name with Chinese Characters is totally legal.

I will reply with a way to disable the chunk name changing after I get up.

I would prefer to focus on how the trouble trigger in your environment.

Github pages works well.

**Comment by Mister-Hope** [comment]
Could you give more info about how your environment triggers an issue with Chinese Charecters? @sonderlau

**Comment by sonderlau** [comment]
> Could you give more info about how your environment triggers an issue with Chinese Charecters? @sonderlau

Sure.

I use a virtual space provided from Taobao, I'm not sure which enviroment he is using now, but i can say it's based on Linux.
So here is the thing, I run `vuepress build docs` and upload all the files, you can check my website on `hziee.site` now.
Here is a screenshot i just made from the website
![image](https://user-images.githubusercontent.com/12829325/103604911-46bd2400-4f0a-11eb-8ff9-d3972e90ee8b.png)

all the js files with Chinese characters responsed with `404` and I checked a js file manually , 
for instance 
`http://hziee.site/assets/js/page-%E5%B9%B3%E6%97%B6%E4%BD%9C%E4%B8%9A%E9%9B%86%E5%90%88--f6a44b54.17e44863.js` 
still 404

and I reviewed the files i built in older theme version , i found all the js files without Chinese characters.
So i hope you can export an option in config, or any other ways to complile js files without Chinese characters.

**Comment by Mister-Hope** [comment]
Sure, I will add a option in the next version.

It will probably landed later today.

**Comment by Mister-Hope** [comment]
BTW, are you using Alibaba Cloud? Which product are you using? "云虚拟主机"？

**Comment by sonderlau** [comment]
> BTW, are you using Alibaba Cloud? Which product are you using? "云虚拟主机"？

idk, an anonymous provider , just for cheap. But it still usable (maybe

**Comment by Mister-Hope** [comment]
> > BTW, are you using Alibaba Cloud? Which product are you using? "云虚拟主机"？
> 
> idk, an anonymous provider , just for cheap. But it still usable (maybe

 😥Never heard of it.

**Comment by sonderlau** [comment]
Thanks man, it works  : )
