### ISSUE TITLE
[Bug]移动端渲染问题

### ISSUE THREAD

**Issue by tenngoxars** [Mister-Hope/vuepress-theme-hope#550]
**Describe the bug**
如 Web 端某一文章的链接为 `/xx/xxx` ，移动端则会渲染为 `/xx/xxx.html`，访问时会出现 404 提示，手动将移动端链接改为 `/xx/xxx`则可正常访问

**Comment by tenngoxars** [comment]
无法准确复现，关闭 issue

**Comment by Mister-Hope** [comment]
我不知道你是不是访问的是中文tag或者中文category的页面，如果是，这是一个和vue-router与vuepress-plugin-blog相关的bug。

我已经提出了相关issue。
