### ISSUE TITLE
页面滚动的时候，侧栏的锚点标题没有对应激活

### ISSUE THREAD

**Issue by yesixuan** [Mister-Hope/vuepress-theme-hope#56]
1、页面滚动的时候，侧栏的锚点标题没有对应激活

2、切换主题色的时候，滚动条的颜色没有变

**Comment by Mister-Hope** [comment]
> 1、页面滚动的时候，侧栏的锚点标题没有对应激活

This feature is fixed in [b0f210](https://github.com/Mister-Hope/vuepress-theme-hope/commit/b0f210c26d21c7a2d00c7080ac174b3ba4839531)

I forgot to add this plugin after the theme stopped to extend `@vuepress/theme-default`.

**Comment by Mister-Hope** [comment]
> 2、切换主题色的时候，滚动条的颜色没有变

The sidebar and other scollbar color is based on the theme color in [a802b0d](https://github.com/Mister-Hope/vuepress-theme-hope/commit/a802b0d3c9bfd8382172c0da4a83b7db11fafb96)

But for the main scrollbar on the right, I have no idea how to change it.

**Comment by Mister-Hope** [comment]
A new version `0.1.0-RC1` has been released, it should fix your issue

**Comment by yesixuan** [comment]
> > 2、切换主题色的时候，滚动条的颜色没有变
> 
> The sidebar and other scollbar color is based on the theme color in [a802b0d](https://github.com/Mister-Hope/vuepress-theme-hope/commit/a802b0d3c9bfd8382172c0da4a83b7db11fafb96)
> 
> But for the main scrollbar on the right, I have no idea how to change it.

你可以通过 css 变量的方式来改变全局的滚动条颜色
![image](https://user-images.githubusercontent.com/22050621/77286844-215e8100-6d0f-11ea-8d23-b921f666e2ef.png)
就像这样
```css
::-webkit-scrollbar {
       color: var(theme-color)
}
```
这种方式不仅可以用来改滚动条，也包括昼夜模式切换、主题色切换。
比起改变容器元素的样式，子元素继承的方式更全面，也更灵活。

**Comment by Mister-Hope** [comment]
> > > 2、切换主题色的时候，滚动条的颜色没有变
> > 
> > 
> > The sidebar and other scollbar color is based on the theme color in [a802b0d](https://github.com/Mister-Hope/vuepress-theme-hope/commit/a802b0d3c9bfd8382172c0da4a83b7db11fafb96)
> > But for the main scrollbar on the right, I have no idea how to change it.
> 
> 你可以通过 css 变量的方式来改变全局的滚动条颜色
> ![image](https://user-images.githubusercontent.com/22050621/77286844-215e8100-6d0f-11ea-8d23-b921f666e2ef.png)
> 就像这样
> 
> ```css
> ::-webkit-scrollbar {
>        color: var(theme-color)
> }
> ```
> 
> 这种方式不仅可以用来改滚动条，也包括昼夜模式切换、主题色切换。
> 比起改变容器元素的样式，子元素继承的方式更全面，也更灵活。

Thanks for the advice 😃 , I will rebuild the theme-color and nightmode feature before 0.3.0

**Comment by Mister-Hope** [comment]
The feature is in progress on [theme-color branch](https://github.com/Mister-Hope/vuepress-theme-hope/tree/theme-color), and will move to #57 for checking.
