### ISSUE TITLE
[Bug]打包时报错：Error rendering /timeline/、Error rendering /tag/

### ISSUE THREAD

**Issue by melogra** [Mister-Hope/vuepress-theme-hope#561]
### bug描述
```yarn docs:dev```时运行正常，```yarn docs:build```控制台报以下错误。
> error Error rendering /timeline/: false
  undefined
  error Error rendering /tag/: false
  undefined
  / do not have valid sidebar config
  / do not have valid sidebar config
  / do not have valid sidebar config
  / do not have valid sidebar config
   TypeError: Cannot read property 'timelineText' of undefined
   at Proxy.get (Timeline.ts:12:36)
   at Proxy.render (node_modules/vuepress-theme-hope/components/Blog/Timeline.vue?55ac:1:242)
### 我的配置
```javascript
// .vuepress/config.js
module.exports = {
  plugins: [
    'mermaidjs',
    [
      'md-enhance',
      {
        tex: true,
        flowchart: true,
      },
    ],
  ],
  theme: 'vuepress-theme-hope',
  // themeConfig下没有与timeline或tag相关的配置
 // 所有文章的frontmatter 也没有相关设置
}
```
*我注意到以下这段代码，不知道是不是blog判空的问题*
```javascript
// components/Blog/Timeline.js
get hint() {
        return ((this.$themeConfig.blog && this.$themeConfig.blog.timeline) ||
            // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
            this.$themeLocaleConfig.blog.timelineText ||
            getDefaultLocale().blog.timelineText);
    }
```

**Comment by melogra** [comment]
将```theme.blog```设为```false```能通过。
PS：想请教下```$themeLocaleConfig```是在哪里被定义和赋值的。

**Comment by Mister-Hope** [comment]
感谢提供详细的日志与配置。我看一下

附：大哥你这在修仙啊。

**Comment by melogra** [comment]
感谢，已解决。
我已修仙多年：）

**Comment by onRoadLookBeauty** [comment]
我也有相同问题,请问具体是怎么解决的
