### ISSUE TITLE
[Feature Request]为流程图提供多一种起始、结束标签

### ISSUE THREAD

**Issue by melogra** [Mister-Hope/vuepress-theme-hope#562]
**Describe the feature and why you wanted**
typora是一款很好用的markdown编辑工具，但是typora中写流程图或其他代码是

\``` flow
// 流程图代码
\```

\```javascript
// javascript 代码
\```

![image](https://user-images.githubusercontent.com/45912760/105321361-4effa980-5c02-11eb-9130-8d17667e372e.png)

这种形式。
希望能兼容它。

**Comment by Mister-Hope** [comment]
Vuepress is using [prism.js](https://prismjs.com/) to highlight it's code block, and it has no api to let themes, plugins or users to config prism.js.

---

Addtional info:

The flow language is already supported by prism.js: See https://prismjs.com/#supported-languages

And from the source code (See https://github.com/PrismJS/prism/blob/master/components/prism-flow.js), it's definitly not using flowchart.js to provide a flowchart. Instead, it propably represents [lfow](https://flow.org/en/docs/getting-started/) (I am not sure)

**Comment by Mister-Hope** [comment]
翻译:

Vuepress正在使用 [prism.js](https://prismjs.com/) 高亮其代码块，它没有提供可让主题，插件或用户配置prism.js的api。

因此，这不是一个可行的功能请求，我将其标记为 `wontfix` 并将其关闭。

---

附加信息：

prism.js 已经支持  `flow` 语言高亮：请参阅 https://prismjs.com/#supported-languages

并且从源代码（请参阅https://github.com/PrismJS/prism/blob/master/components/prism-flow.js）来看，它绝对没有使用 flowchart.js 提供流程图。 相反，它可能代表 [flow](https://flow.org/en/docs/getting-started/)（我不确定）

**Comment by Mister-Hope** [comment]
理论上我可以配置 markdown-it，重写高亮代码规则，即“先检出 flow 语言并使用 flowchart 渲染，再将其他交付给  prism.js“。

但是这意味着我要覆盖掉整个 markdown-it 的 fence-block 规则，而且我的插件也必须引入 prism.js 并完成高亮逻辑，破坏性很大。这可能会导致与其他插件冲突，所以目前靠说，我并不会考虑这样做。

**Comment by Mister-Hope** [comment]
This feature will be added in 1.13.0. And `@flowstart @flowend` will be no longer supported
