### ISSUE TITLE
照你的教程安装主题，各种报错

### ISSUE THREAD

**Issue by jimixy** [Mister-Hope/vuepress-theme-hope#70]
1. 提示 typescript 模块没有找到，然后我安装了 typescript

2. 
![image](https://user-images.githubusercontent.com/21176977/77871990-4f484600-7278-11ea-93ef-67cc0a71ddc7.png)

3. 
![image](https://user-images.githubusercontent.com/21176977/77872025-6424d980-7278-11ea-95fe-0e0abe542868.png)

我的配置
```js
const resolve = require('vuepress-theme-hope/resolve');

module.exports = resolve({
  base: '/vue-code/',
  title: 'vue-next analysis',
});
```

tsconfig.ts
```json
{
  "compilerOptions": {
    "types": [
      "@mr-hope/vuepress-theme-types",
      "vuepress-types"
    ]
  },
  "include": [
    // 这个 ts 文件从哪儿来的？后来我把这行删掉还是报错
    "src/.vuepress/enhanceApp.ts"
  ]
}
```

**Comment by Mister-Hope** [comment]
你需要至少在你的项目里包含一个ts文件，你在根目录创建个空的a.ts都行

**Comment by jimixy** [comment]
> 你需要至少在你的项目里包含一个ts文件，你在根目录创建个空的a.ts都行
> 
> 这个问题是webpack和ts-loader导致的，ts-loader会默认读取工作目录下的tsconfig.json再向上递归，如果根据tsconfig里面的配置在工作区找不到任何匹配的ts文件，ts-loader就会提示你找不到匹配的ts文件并认为你的配置不合法。这样webpack在处理引入模块里的ts文件时仍然会提示你tsconfig.json不合法，不会正确载入ts。

终于安装好了。你文档上的安装教程太过简陋了，来说说我遇到的坑吧

1. ts 依赖需要安装
2. 项目需要自建一个ts 文件
3. tsconfig 文件的include 需要指向 这个 ts 文件
4. tsconfig 添加 "experimentalDecorators": true 启动装饰器特性

建议完善文档

**Comment by Mister-Hope** [comment]
![Screenshot_20200331-095020](https://user-images.githubusercontent.com/33315834/77978652-3356aa00-7335-11ea-8993-a3d3808eda26.jpg)
BTW你可能忽略了这个。

不过1和4我的确忘记注明了

**Comment by Mister-Hope** [comment]
我再解释一下，没有默认依赖typescript是考虑到很多人会在这个主题基础上再稍微自定义一些，工作区可能有不一样的typescript版本，所以设成了peerDependencies，这个没特殊注明的确是我的锅。

另外，vue2的ts一般会用到vue-property-decorator，它里面就是依靠装饰器来实现的。这我也是真忘了提醒一下。

**Comment by Mister-Hope** [comment]
新的文档已经自动部署，里面应该对主题的安装和使用做了更加详尽的介绍。再次感谢您的建议。👍
