### ISSUE TITLE
建议去除用户端的 typescript 强依赖

### ISSUE THREAD

**Issue by jimixy** [Mister-Hope/vuepress-theme-hope#73]
使用 ts 来开发 vuepress 主题是主题开发者的技术栈选择问题。
但 ts 不该成为主题使用者必须要使用的特性和依赖

就像我写一个 ts 写一个 npm 包，最终打包出来给用户使用的一定是一个编译之后的 js 文件

大部分用户使用 vuepress 只是想简单写文档，他们不想也不应该关心 ts 依赖和配置的问题

**Comment by Mister-Hope** [comment]
这个问题目前无法解决。用ts写的vue文件无法转换成js

**Comment by Mister-Hope** [comment]
等到vue3推出以后，ts和js的写法差距几乎消失的时候，也许可以把ts的vue文件转换成js的vue。文件，那样还有可能会去除 ts依赖。

**Comment by jimixy** [comment]
> 这个问题目前无法解决。因为这不是一个简单的 js 包。主题内用 ts 写的 vue 文件无法转换成 js，只能在引入时交给 ts-loader 动态处理。
> 
> 等到vue3推出以后，ts和js的写法差距几乎消失的时候，也许可以把ts的vue文件转换成js的vue文件，那样还有可能会去除 ts依赖。

其实vue 文件也是可以打包成 纯js 的,就像element-ui是可以作为js包被 html 页面直接引用的
![image](https://user-images.githubusercontent.com/21176977/77985606-82a5d600-7347-11ea-9923-7ed1b0875024.png)

**Comment by Mister-Hope** [comment]
> 主题内用 ts 写的 vue 文件无法转换成 js.

我已经说过了，element-ui 是用js写的。

另外打包成一个文件会失去 vuepress [继承主题](https://v1.vuepress.vuejs.org/zh/theme/inheritance.html#%E5%8A%A8%E6%9C%BA) 的特性。

P.S: 我一不小心直接把你的评论改了。

**Comment by Mister-Hope** [comment]
ts-loader 并不支持直接配置 `compilerOptions` ，只支持传递 tsconfig.json 路径，并且由于主题被拆分成多个 package，而且用户的依赖结构不确定，目前是没有办法内置一个 tsconfig.json 交给 ts-lodaer 的。

详见：https://github.com/TypeStrong/ts-loader#options

这个问题我也嫌麻烦，但是目前无论是我还是社区 [vuepress-plugin-typescript](https://vuepress.github.io/zh/plugins/typescript/) 都没办法解决。而且任何一个想要使用 ts 的 vue 项目也必须如此给予一个合理的 tsconfig.json 配置。我当时也是想了好久，实在找不到办法，才做成这样。

**Comment by Mister-Hope** [comment]
同时也正因为 ts 版本的 vue 文件存在的这些问题，目前所有的 vue 组件库都是用 js 写的，不然也遇到跟我同样的问题，归根结底还是 vue2 对 ts 支持不好的锅。

按照现在 vuepress 官方的进度(几乎没进度)，即使 vue3 推出了， vuepress 什么时候能跟进还是一个问题，保守估计 3个月到半年，所以这是一个一时半会没法解决的问题。

**Comment by Mister-Hope** [comment]
@jimixy 总结一下，vue2对ts屎一样的支持是一口大黑锅，目前大多数项目不敢碰这口大黑锅干脆不用ts，如果用了这口大黑锅就得扣给用户，不知道我的解释您是否看明白了没？😂

**Comment by jimixy** [comment]
好吧，vue2 中 ts 的写法是挺奇葩的。
那有没有计划在主题中去掉 ts？

**Comment by Mister-Hope** [comment]
暂时没有，0.0.x版本我的主题还是用js写的呢，后来太多配置记不清，为了ts的interface提示后来迁移过来了。目前我的确想不到什么好的解决方案。肯定不会迁移过去了。vue3快发了，如果vue3可以转换，我肯定会转换过去。如果不支持的话，现在还不确定，反正是要重写的，ts的接口和类型推导的确写起来很舒服，不想放弃用js写。

Angular直接强制ts，react的tsx可以转jsx，只有vue异常蛋疼。。。。。。

**Comment by Mister-Hope** [comment]
Close by release of 0.7.0-alpha.1
