### ISSUE TITLE
Line numbers are not aligned with the code in the code block

### ISSUE THREAD

**Issue by ChungZH** [Mister-Hope/vuepress-theme-hope#80]
![image](https://user-images.githubusercontent.com/42088872/78421890-df79f700-768d-11ea-8cc0-ffc53ac2bbc2.png)

Browser: Edge
OS: Windows 10

By the way, I realllllly hope you can publish your plugin of Dark Mode! I LOVE this feature. Please ASAP,  thank you very much :smiley:

**Comment by Mister-Hope** [comment]
@mr-hope/vuepress-plugin-theme-color is exactly what you want.

**Comment by ChungZH** [comment]
Cool, love it! Thank you! :heart:

**Comment by Mister-Hope** [comment]
The issue was fixed in `0.1.0-rc.8`. 😃

**Comment by Mister-Hope** [comment]
I rebuild the theme-color and darkmode in `0.1.0-rc.9`.

Now the feature is based on css vars, and fully support with `prefer-color-scheme`.
